### ISSUE TITLE
Remove italic on 'arrow' at functions definitions

### ISSUE THREAD

**Issue by joaoevangelista** [dracula/visual-studio-code#10]
Using javascript, maybe typescript too, when we declare an anonymous function or a lambda the arrow operator `=>` is italic.
Since most of fonts do not support ligatures such as Fira code, nor support italics, for a better alignment I think is better to keep them normal.

**Comment by dsifford** [comment]
@joaoevangelista Good call. Will fix later this evening.

**Comment by joaoevangelista** [comment]
Awesome!
