### ISSUE TITLE
Inconsistent editor background color

### ISSUE THREAD

**Issue by seiks** [dracula/visual-studio-code#100]
Hello. 👋 

There's something weird about the way Dracula renders the **editor background color**.

If you look closely to the right side of the image, you can see that there is a cut-off point from which the background changes its shade ever so slightly.

<img width="903" alt="0" src="https://user-images.githubusercontent.com/22685871/53676857-c9db1680-3cb0-11e9-91e6-720e2b22d6e9.png">

Here's a zoomed up version. You should see a darker rectangle at the top right portion of the frame, and at the bottom right portion.

<img width="449" alt="1" src="https://user-images.githubusercontent.com/22685871/53676858-c9db1680-3cb0-11e9-9c2a-f31149a0d4a5.png">

Here's an example where I've drawn out the contour with arrows.

<img width="1041" alt="4" src="https://user-images.githubusercontent.com/22685871/53676909-4f5ec680-3cb1-11e9-80a1-e3d52f85a2a7.png">

This only happens on Dracula, as far as I am aware. I've tried out the default themes for example, and they show no rendering problems like this.

<img width="949" alt="2" src="https://user-images.githubusercontent.com/22685871/53676860-ca73ad00-3cb0-11e9-9221-2004cded9542.png">
<img width="500" alt="3" src="https://user-images.githubusercontent.com/22685871/53676862-ca73ad00-3cb0-11e9-8bd9-cc7894529452.png">

Tests performed:

+ Observed while working on macOS.
+ Observed after disabling all extensions.
+ Observed after resetting all user settings.
+ Observed on 2 different display monitors.

**Comment by seiks** [comment]
I realized some time ago that this problem may not be noticeable on all monitors due to poor color space. Here's an edited version of the above image.

<img width="1041" alt="53676909-4f5ec680-3cb1-11e9-80a1-e3d52f85a2a7" src="https://user-images.githubusercontent.com/22685871/56057520-a8695200-5d67-11e9-9592-4c31271f1090.png">

I also thought that this problem existed on all platforms, but I suspect it may only exist on macOS.

**Comment by dsifford** [comment]
This is a feature, not a bug. 

The differing colors adds depth and allows you to see hard differentiation between the tab bar, sidebar, tabs, etc.

You're free to adjust in your user settings if you'd prefer to make them all the same color.

**Comment by dsifford** [comment]
Oh, whoops.. Misread that. 

Not sure what could be causing that issue. Might be a paint issue with electron on darwin. Not sure.

You might not be noticing it in the default themes because the dark color is darker and less saturated.

**Comment by seiks** [comment]
It might be an upstream issue. I'll try to find some time and dig in deeper to renderer code paths, perhaps also try to replicate this with other themes. Your point about saturation gave me an idea to try.

**Comment by seiks** [comment]
The key word is saturation.

**One Dark Pro (difference enhanced)**
<img width="1280" alt="Näyttökuva 2019-04-12 kello 21 42 33" src="https://user-images.githubusercontent.com/22685871/56059384-9f2eb400-5d6c-11e9-8f03-2c4d3f5f81b7.png">

**Tomorrow Night Blue (difference enhanced)**
<img width="1280" alt="Näyttökuva 2019-04-12 kello 21 43 54" src="https://user-images.githubusercontent.com/22685871/56059385-9f2eb400-5d6c-11e9-845d-aae8c61885ae.png">

**Kimble Dark (normal)**
<img width="1280" alt="Näyttökuva 2019-04-12 kello 21 45 36" src="https://user-images.githubusercontent.com/22685871/56059386-9f2eb400-5d6c-11e9-9ab6-75b705041c8d.png">

**Kimble Dark (possible to find artifact after _saturation_ boost)**
<img width="1280" alt="asdf" src="https://user-images.githubusercontent.com/22685871/56059514-eb79f400-5d6c-11e9-9145-ac3e01e37e78.png">

Definitely an upstream issue. Thanks for the tip about saturation.

**Comment by seiks** [comment]
Active issue upstream: https://github.com/Microsoft/vscode/issues/71117
