### ISSUE TITLE
Some colors in README.md's screenshot and some in a real vscode is not the same

### ISSUE THREAD

**Issue by black-black-cat** [dracula/visual-studio-code#106]
hi there,

Some colors in `https://draculatheme.com/assets/img/screenshots/vscode.png` and some colors in a real vscode is not the same. 

It is not convenient for people know the real code syntax color highlights in a vscode, if they just take a look at the README.md's screenshot or the screenshot on `https://draculatheme.com/visual-studio-code/`.

![微信图片_20190508101856](https://user-images.githubusercontent.com/15521864/57344975-dfbafb00-717b-11e9-867c-470f42da6035.png)

**Comment by lucasmortoni** [comment]
experimenting the same in "document" element in JS, where the keyword does not get the right color.

<img width="445" alt="Screen Shot 2019-05-08 at 12 58 11" src="https://user-images.githubusercontent.com/20991871/57390031-d0df4300-7191-11e9-9ff3-b5d8c39fd1d8.png">

usually gets some kind of purple and functions from "document" are not green, but blue. like this:

<img width="458" alt="Screen Shot 2019-05-08 at 10 10 31" src="https://user-images.githubusercontent.com/20991871/57390086-ec4a4e00-7191-11e9-80b0-9a421f079247.png">

**Comment by dsifford** [comment]
README is outdated. The extension implements the correct colors. PRs accepted if you feel like updating the screenshot.

**Comment by dsifford** [comment]
I'll keep this issue open until the screenshot gets updated.
