### ISSUE TITLE
Font Screenshot

### ISSUE THREAD

**Issue by Goatmaster** [dracula/visual-studio-code#107]
Hey,

just wanted to know what font is used in the screenshots.

Best.

**Comment by dsifford** [comment]
I'm not entirely sure. That screenshot originates from upstream in the main repo I think. If I had to guess, I'd say it's probably dejavu mono, liberation mono, droid mono, or ubuntu's default monospaced font based on how the letter `i` is formed, but your guess is as good as mine.
