### ISSUE TITLE
Unable to see text in search result 

### ISSUE THREAD

**Issue by nguyenhuumy** [dracula/visual-studio-code#11]
<img width="452" alt="screen shot 2017-03-03 at 6 45 14 pm" src="https://cloud.githubusercontent.com/assets/5990387/23548281/ae6c70c2-0041-11e7-874c-38dd3627656c.png">

If your code has dark blue color, the highlight text in search result make it unseen

**Comment by dsifford** [comment]
@nguyenhuumy Good catch... Fix coming shortly. 👍

**Comment by dsifford** [comment]
Fixed in #13
