### ISSUE TITLE
Triple closing type brackets break syntax highlighting for TypeScript 

### ISSUE THREAD

**Issue by vshab** [dracula/visual-studio-code#111]
Hello!

The following code breaks code highlighting beneath:
```ts
export class Foo<T> {
  private x?: number;

  bar<P extends Partial<Readonly<T>>>(arg: P): void;
  bar<P extends Partial<Readonly<T>>>(arg: () => P): void {
    if (typeof arg === 'object') {
      console.log(arg);
    } else if (typeof arg === 'function') {
      console.log(arg());
    } else {
      throw new Error();
    }

    this.x = 10;
  }
}
```

How it looks (wrong):
<img width="601" alt="Screenshot 2019-07-06 at 19 55 47" src="https://user-images.githubusercontent.com/6755908/60756523-7dba2d00-a028-11e9-96e6-768c5e392d0f.png">

How it looks with double closing type brackets (right):
<img width="563" alt="Screenshot 2019-07-06 at 19 56 04" src="https://user-images.githubusercontent.com/6755908/60756533-8f033980-a028-11e9-91fb-09207a70047b.png">

MacOS
VSCode Version 1.36.0
Dracula 2.18.0

**Comment by dsifford** [comment]
This should be posted in https://github.com/Microsoft/TypeScript-TmLanguage/

Closing this as it's out of scope.
