### ISSUE TITLE
Custom function highlighting for R

### ISSUE THREAD

**Issue by nathaneastwood** [dracula/visual-studio-code#112]
Is it possible to get function highlighting for custom functionality for R? I have included a screenshot below whereby `unique()` is a base R function; `data.table()` is a function from the `data.table` package; and `UpdateAndGetCachedData()` is a custom function from one of my own packages.

![image](https://user-images.githubusercontent.com/9799530/61116303-7665aa00-a494-11e9-8950-38b23ed4ca6a.png)

The RStudio editor manages to handle this like so:

![image](https://user-images.githubusercontent.com/9799530/61116416-b3ca3780-a494-11e9-97f5-f1d2c8988a81.png)

I appreciate that the dracula team don't manage (I think) the RStudio dracula theme but it would be nice to get these RStudio features ported to VS Code.

**Comment by dsifford** [comment]
The R syntax in vscode is pulled from [here](https://github.com/Ikuyadeu/vscode-R). So if you'd like to see changes with how syntax highlighting is applied, you'll have to do it there.
