### ISSUE TITLE
Color within parameter info box

### ISSUE THREAD

**Issue by skube** [dracula/visual-studio-code#114]
I seem to have color within the IntelliSense box but not for the parameter info.

Initial IntelliSense box (color coded)
<img width="954" alt="Screen Shot 2019-09-29 at 9 27 30 AM" src="https://user-images.githubusercontent.com/146396/65833914-95a9f180-e2a3-11e9-9c2e-67cf379c724d.png">

Parameter info (monochrome)
<img width="640" alt="Screen Shot 2019-09-29 at 9 27 51 AM" src="https://user-images.githubusercontent.com/146396/65833913-95115b00-e2a3-11e9-863b-92b13cd257a5.png">

**Comment by dsifford** [comment]
Not totally sure. Does this happen on all themes or just this one?

**Comment by skube** [comment]
As far as I can tell, all themes.

**Comment by dsifford** [comment]
Hm, yeah then this will probably be something that would need to be brought up in the main vscode repo. Maybe do a quick search there to see if it's already been brought up?

**Comment by skube** [comment]
OK thanks for responding!
