### ISSUE TITLE
TM scope match when using Babel JavaScript extension

### ISSUE THREAD

**Issue by black-black-cat** [dracula/visual-studio-code#117]
Hey buddy.

![chrome_6bCQsCGnwo](https://user-images.githubusercontent.com/15521864/66642655-bda83600-ec4f-11e9-96dc-50341d32a918.png)

When I installed [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) to change the default js syntax highlight in vscode. I found the newer color of class name scope turn to match `entity.name.class`, which is not in the theme's json.

**Comment by black-black-cat** [comment]
PR is ready in #118 👌

**Comment by dsifford** [comment]
Closed in #118
