### ISSUE TITLE
Improve semantic highlighting across all languages

### ISSUE THREAD

**Issue by dsifford** [dracula/visual-studio-code#12]
# The Problem

Dracula does not have an official guideline when it comes to semantic highlighting. Because of this, you might notice that there is really no uniformity between Dracula theme implementations, and even between languages within the same Dracula theme implementation (including this one!).

An example of this behavior can be seen by comparing `JSON` and `yaml` languages below.

### Before

JSON |  Yaml
--- | ---
<img src="https://i.imgur.com/I6fuSOu.png" width="100%"> | <img src="https://i.imgur.com/uHqZqyE.png" width="100%">

# The solution

The theme implementation will need to be scrutinized so that the semantic highlighting across all languages is uniform. 

An example of this solution applied to `JSON` and `yaml` can be seen below.

### After
JSON |  Yaml
--- | ---
<img src="https://i.imgur.com/ougY2zJ.png" width="100%"> | <img src="https://i.imgur.com/6JvLskI.png" width="100%">

# Community Feedback

I'd prefer to make these uniformity adjustments as democratic as possible. I understand that everybody has their own personal tastes when it comes to how things should be highlighted. So, in an effort to be as fair as possible, I ask that you please leave your feedback and suggestions below so that the changes can be the result of a large user consensus.

### Changes that land in updates are not final

If a particular change is made that you don't like, please let me know and we can discuss!

# Progress

Key | Value
--- | ---
❌ | Not started
🚧 | Work-in-progress
☑️ | Finished

Language | Status
--- | ---
`c` | ❌ 
`c++` | ❌ 
`clojure` | ❌ 
`coffeescript` | ❌
`c#` | ❌ 
`css` | ❌ 
`f#` | ❌ 
`go` | ❌ 
`groovy` | ❌ 
`java` | ❌ 
`javascript` | 🚧  
`json` | ☑️ 
`less` | ❌ 
`lua` | ❌ 
`make` | ❌ 
`obj-c` | ❌ 
`perl` | ❌ 
`php` | ❌ 
`powershell` | ❌ 
`python` | ❌ 
`R` | ❌ 
`ruby` | ❌ 
`rust` | ❌ 
`sass` | ❌ 
`shell (bash)` | ❌ 
`swift` | ❌ 
`toml` | ❌ 
`typescript` | 🚧 
`yaml` | ☑️

**Comment by dsifford** [comment]
@wprater One thing I've been mulling over is how to approach highlighting the various types of constants across languages.

Right now (for the most part) numeric and language constants are highlighted purple.

So, if we take JS as an example, that would be these...
```js
1 2 3 4 5 6 7 8 9 0
1.123
true
false
__dirname
__filename
NaN
undefined
null
// ...etc
```

I'm wondering if this should be broken down into two separate entities: numeric constants being purple and language constants being green?

This isn't really a problem with JS, but other languages have a much broader textmate scope when it comes to language constants so the purple color carries over much further.

**Comment by wprater** [comment]
I like the idea of breaking them down more.  especially the language keywords.  numbers, strings, language constructs, and constants should all be different, in my opinion.

wish I could give me more advice now.  Ive been mainly using Monokai 80s and Material Ocean, which seem to do quite a but of the breakdown.  However, Ive been in JS land recently, less so in Python or Ruby.

did you know about the new TM scope selector for developers that you can activate?

**Comment by dsifford** [comment]
> I like the idea of breaking them down more. especially the language keywords. numbers, strings, language constructs, and constants should all be different, in my opinion.

Yeah, agree that there should be distinction. I suppose the goal is to avoid overdoing it. I imagine some of the Dracula users out there appreciate the "mid-range minimalism" of how the theme sits currently.

>  Ive been mainly using Monokai 80s and Material Ocean, which seem to do quite a but of the breakdown.

I suppose I could download those themes and see if I can use them for inspiration.

> did you know about the new TM scope selector for developers that you can activate?

Nope. Can you clarify?

**Comment by wprater** [comment]
sorry, for the massive delay!

I thought the TM scope selector could be helpful for you!

![image](https://cloud.githubusercontent.com/assets/10452/24263265/e909b564-0fb9-11e7-99e0-d0d38d21a591.png)

**Comment by wprater** [comment]
> Yeah, agree that there should be distinction. I suppose the goal is to avoid overdoing it. I imagine some of the Dracula users out there appreciate the "mid-range minimalism" of how the theme sits currently.

Im not familiar enough with Dracula to know its design inspiration, so perhaps the other themes are not a good example.

**Comment by dsifford** [comment]
@wprater Ah, yeah nevermind I did know about that scope inspector tool. Very handy indeed!

**Comment by ajitid** [comment]
Please add different color for escape characters. Python, HTML, C/C++,  I found it nowhere. :-/

**Comment by dsifford** [comment]
@ajitid Added to `v1.12.0`. Good suggestion 👍

**Comment by ajitid** [comment]
You still missed to add it for HTML. I typed &mdash but saw no change.

**Comment by dsifford** [comment]
That's not an escape character, that's an HTML entity

**Comment by dsifford** [comment]
@ajitid Added html entity highlighting in 1.13.0.

**Comment by matt3224** [comment]
Hey, can we colour php html better, so that php tags and vars and text content in html tags have different colours, as currently they are all white.

![screen shot 2017-05-07 at 1 52 30 pm](https://cloud.githubusercontent.com/assets/2401925/25781206/9559800a-332e-11e7-9ced-1905497c4932.png)

Thanks!

**Comment by dsifford** [comment]
@matt3224 

![image](https://cloud.githubusercontent.com/assets/5240018/25782647/0d519fbe-331d-11e7-90fb-638cde947d46.png)

Acceptable? Any color suggestions?

**Comment by dsifford** [comment]
^not totally sold on this by the way. It's sort of a disaster in a real-world scenario


![image](https://cloud.githubusercontent.com/assets/5240018/25782701/fff5231c-331d-11e7-90c2-d79b60d0e79e.png)

**Comment by matt3224** [comment]
Is it a disaster due to the nested tags? red is a little jarring tough to pick a colour though!

**Comment by dsifford** [comment]
Just seems like too much chaos. Color looks like it's peppered in without much regard in the snippet I shared (which may or may not also be due to the chaos of the snippet).

Open to your ideas though @matt3224

**Comment by matt3224** [comment]
Looking at the coda variant its more pink and html tags are all pink, which is less madness but perhaps we make it so php tags are the purple, vars in white and make the whole of the html tag including the arrows and forward slash the pink?

That combo may look more succinct... perhaps 😉

![screen shot 2017-05-07 at 7 28 11 pm](https://cloud.githubusercontent.com/assets/2401925/25783894/b9dfc0c4-335b-11e7-8ec5-7e767a8e7cb3.png)

**Comment by dsifford** [comment]
@matt3224 Let me mull this over some more and get back with you. I'd prefer to keep the html tags as-is because it currently matches its JSX counterpart (and I personally like the look of the white slash).

I think you're on the right track though. I'll play around with it some more this week and report back with some ideas.

**Comment by matt3224** [comment]
Great, thanks @dsifford

**Comment by dsifford** [comment]
RFC submitted here: https://github.com/dracula/dracula-theme/issues/232

Fully standardized and spec-compliant implementation of this theme will land on the next release. 👍
