### ISSUE TITLE
Find widget border

### ISSUE THREAD

**Issue by jaminthorns** [dracula/visual-studio-code#120]
The find widget has an (in my opinion) unnecessary border that throws off the spacing and balance of the UI:

![Screen Shot 2019-11-01 at 5 41 33 PM](https://user-images.githubusercontent.com/6618434/68060707-887f8880-fccf-11e9-9c4c-00020d15842a.png)

Compare this to the find widget when using the Dark+ theme:

![Screen Shot 2019-11-01 at 5 40 21 PM](https://user-images.githubusercontent.com/6618434/68060731-9a612b80-fccf-11e9-86c4-2f3c8c6df10a.png)

**Comment by dsifford** [comment]
Feel free to open a PR :+1:
