### ISSUE TITLE
Dracula theme in Visual Studio Code Jupyter Notebook - Black cursor

### ISSUE THREAD

**Issue by JacobEFO** [dracula/visual-studio-code#124]
Hey fellow Draculas,

I absolutely love your theme and have been using it for quite a while.

However, I recently noted that when trying to use a Jupyter Notebook in VSCode using Dracula color theme, the cursor becomes black, as shown in the [link](https://imgur.com/a/mjOEusJ). Note at the end of the second block, the cursor is all black.

I am not sure, how this issue arises, but have any of you encountered something along those lines, and may you have any solutions to it?

Best regards

**Comment by dsifford** [comment]
Definitely an odd one... 

Does this happen with all themes or just this one?

**Comment by JacobEFO** [comment]
The other themes I tested all have white cursor in both .py and .ipynb files, but Dracula has a black in .ipynb and white in .py.

**Comment by dsifford** [comment]
I got it figured out @JacobEFO. Give me a day or two and I'll get a fix for this pushed out.

**Comment by JacobEFO** [comment]
Ah fantastic. Looking forward to it ;)

**Comment by dsifford** [comment]
Fixed in 2aa183123b7fec4dc890b23e847f8de85f8be153.

**Comment by azukacchi** [comment]
Hello, I recently installed this theme. Is the dark cursor when working with Jupyter Notebook the default setting now? Because I have the same problem, the cursor is dark in .ipynb but white in .py

**Comment by dsifford** [comment]
@azukacchi I just checked and you are correct, the soft variant still had the issue. 

I went ahead and fixed that and and pushing out a release right now that should fix the issue for you. Should show up in vscode in the next few minutes.

**Comment by azukacchi** [comment]
already installed the update. looks great! 👍
