### ISSUE TITLE
Vue broken ::v-deep highlighting

### ISSUE THREAD

**Issue by thinkerdu** [dracula/visual-studio-code#125]
![image](https://user-images.githubusercontent.com/28700378/69476879-5ec30880-0e1a-11ea-9779-94611e1c3f46.png)
![image](https://user-images.githubusercontent.com/28700378/69476906-a0ec4a00-0e1a-11ea-8f97-45c39559c51c.png)

**Comment by dsifford** [comment]
Assuming the syntax of the editor where this is happening is `scss`, then this is going to be an issue you'll have to raise with the maintainers there as themes have no control over that.

The scss syntax in vscode is actually pulled from [the atom language-sass repo](https://github.com/atom/language-sass).

**Comment by thinkerdu** [comment]
https://github.com/atom/language-sass/issues/274
