### ISSUE TITLE
Weird background

### ISSUE THREAD

**Issue by rasuru** [dracula/visual-studio-code#126]
Hello, look at the image below. My background is not one consistent colour. I am not sure if this defect is caused by the theme or VS Code. I didn't find anyone experiencing the same issue and VS Code default themes work properly. So I decided to submit an issue. Do you know how to fix this? Thank you in advance!

![image](https://user-images.githubusercontent.com/39127725/70851354-52cce280-1ebe-11ea-9949-a26baa0f0db6.png)

**Comment by dsifford** [comment]
I don't have the time at the moment to check, but IIRC, someone in the past opened a similar issue in this repo and I _believe_ it was an issue with VSCode itself (or maybe electron?). 

For now, try checking through the old issues and let me know if you were able to find the solution or not.

I'd also suggest checking VSCode's issues to see if something came up there as well.

**Comment by rasuru** [comment]
Thank you for you reply! I think this issue is somehow related to my OS. I recently upgraded from Ubuntu 18.04 to 19.04. If I remember right, your theme worked perfectly before and it works on Windows too. So, I will try to figure that out on my own. Thank you again!

**Comment by rasuru** [comment]
Oh, I fixed the problem! I don't know which of these things helped but what I did was:
- Upgrade Electron
- Choose older Nvidia driver version
- Install VS Code Insiders
- Change my Gnome and Gnome Shell themes

**Comment by FelipeBohnertPaetzold** [comment]
@rasuru This problem appears to occur when hardware acceleration is enabled.
Follow these steps and see if the problem is fixed:

**1:** Run `Ctrl + Shift + P` in your VS Code and type *Configure Runtime Arguments*
**2:** Add this line to the json file and save:
```json
{
    "disable-hardware-acceleration": true
}
```
**3:** Restart IDE.
___

This solved the problem for me. Please check and post the result

**Comment by rasuru** [comment]
@FelipeBohnertPaetzold Thank you for your suggestion :+1:  I don't know if it helps, because the issue is already gone and I can't replicate it. And I don't really use VSCode anymore (switched to Vim), but maybe it will help someone :smile:
