### ISSUE TITLE
Syntax Highlighting for each language...

### ISSUE THREAD

**Issue by rediffusion** [dracula/visual-studio-code#128]
## About Syntax.

 First of all th10 for an awesome theme! 🎆
I don't understand why the color syntax for all languages that I use (i.e. - C#, JS, TS, AHK, C++, C, Java, Html, CSS, Python...) is the same?
 Is there a wat to implement for ich language his own different ⚡`Syntax Highlighting`⚡ ?

Regards! 👍✌️

**Comment by dsifford** [comment]
I'm not sure I understand the question you're asking here, but it sounds like you're asking if it's possible to have a different theme for each language? This might be a question better suited for vscode itself, or stack-overflow.

To answer your question: no, this is not possible.

**Comment by rediffusion** [comment]
@dsifford 

0Key, my friend let me explain it another way...

As an example, I'll take the IDE called «[NotePad++](https://notepad-plus-plus.org/downloads/)».
I have a theme called "Plastic Code Wrap". It looks like this:

![image](https://user-images.githubusercontent.com/30071027/71870673-e2fdf080-3127-11ea-8c28-428853d86fee.png)

Now I put here some `code`, then I switch to other languages...

## C#

![image](https://user-images.githubusercontent.com/30071027/71870861-5a338480-3128-11ea-8f6e-cd5d191ade4f.png)

## JavaScript

![image](https://user-images.githubusercontent.com/30071027/71870894-79321680-3128-11ea-83cb-26d711905f0b.png)

## AutoHotkey

![image](https://user-images.githubusercontent.com/30071027/71870922-94048b00-3128-11ea-9bb0-88cf003a5864.png)

## C++

![image](https://user-images.githubusercontent.com/30071027/71870945-a8e11e80-3128-11ea-8b35-b84e162f0b6f.png)

## CSS

![image](https://user-images.githubusercontent.com/30071027/71870978-c57d5680-3128-11ea-9c90-c90aa3fe5a69.png)

## HTML 

![image](https://user-images.githubusercontent.com/30071027/71870995-d29a4580-3128-11ea-864e-8311edc3ce87.png)

Different syntax, color, style, font, weight, brackets... etc.
But in your cool **theme** I see the same shit with all languages. Please help! 🙏
