### ISSUE TITLE
Different background colors on the editor

### ISSUE THREAD

**Issue by mtrojahn** [dracula/visual-studio-code#129]
![Screenshot from 2020-01-10 20-45-26](https://user-images.githubusercontent.com/4460031/72194026-cfce7780-33ea-11ea-8132-0bd4dda33472.png)

I don't know if you can see on the screenshot. But the editor has 2 different background colors. Where there is text the background is a faded version of the default background color.

On the top right and bottom right of the screenshot, you can see the correct background.

You may need to change contrast to see it. The screenshot was taken on PopOS 19, Vscode 1.41.1. All my addons other than Dracula are disabled.

It doesn't happen on a Windows 10 and Vscode 1.41.1

**Comment by mtrojahn** [comment]
I might add that the difference in colors follow the selected line. It usually apply the odd color in steps of 10 lines.

**Comment by dsifford** [comment]
Could this be related to #126?

**Comment by mtrojahn** [comment]
Yep, it's the same problem for sure. I tried switch themes too and nothing happened so I guess it's just one of those things we gotta live with.
