### ISSUE TITLE
Broken highlighting for destructured parameters

### ISSUE THREAD

**Issue by hacknug** [dracula/visual-studio-code#131]
Pretty sure this is an issue somewhere upstream but reporting first here in case y'all know something about it.

Right now the following snippets look different from each other even though they're the same (besides the three extra line breaks).
 
```js
const example = {
  ok: async ({ one: { nested }, two }) => {},
  no: async ({
    one: { nested },
    two,
  }) => {},
}
```

The first issue would be the color of the word `async` which is pink for the first example and green for the second. I'm guessing the syntax is incorrectly assuming that's the name of the function?

The second issue would be the broken highlighting of destructured parameters which is probably caused by the previous one.

This seems to affect most of the themes I've tried (if not all) so it's either something on my end or something coming from upstream. Some seem to not highlight destructured parameters so it looks less broken but is still the same.

Anything we can do to fix this if I'm not the only one experiencing it?

----

<details>
  <summary>EDIT: Just saw things look the same here on GitHub code blocks so…</summary>
	<img src="https://user-images.githubusercontent.com/1107521/73378943-af932980-42c1-11ea-9fb6-3b963df2f39d.png" />
</details>

<details>
  <summary>EDIT 2: Now they don't lol Something is changing on comment update haha</summary>
	<img src="https://user-images.githubusercontent.com/1107521/73378996-c0439f80-42c1-11ea-8009-2a7f8528ae3b.png" />
</details>

<details>
  <summary>EDIT 3: This was probably due to the missing <code>=</code> 🤔 </summary>
</details>

**Comment by dsifford** [comment]
Hey @hacknug!

Yep, this is going to be an upstream issue. Per [the syntax defined in vscode](https://github.com/microsoft/vscode/blob/5936cf11a9f250648549ee73ac366d460f862752/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L2-L6) you should report this issue here: https://github.com/Microsoft/TypeScript-TmLanguage

Not much we can do from the theme end unfortunately.

**Comment by dsifford** [comment]
That said, if the scopes are correct but the highlighting is incorrect, reopen. We can totally fix that. (sorry may have jumped the gun!)
