### ISSUE TITLE
February 2020 update broke typescript and javascript syntax

### ISSUE THREAD

**Issue by sergiz** [dracula/visual-studio-code#132]
There were some changes introducted in February 2020 that break highligting for JS.

More info: https://github.com/microsoft/vscode/issues/92308

**Comment by leandrocunha** [comment]
You are right @sergiz a strange behavior for me here. Look the component written in white color:
<img width="403" alt="Screenshot 2020-03-10 at 09 46 51" src="https://user-images.githubusercontent.com/1820920/76294999-2b669580-62b4-11ea-8cb2-35fd9bf6b7de.png">

**Comment by DoanVanThuong** [comment]
![image](https://user-images.githubusercontent.com/26888633/76301055-435c0a80-62f0-11ea-8670-4c49d2ba99df.png)

**Comment by sergiz** [comment]
Of course you have the same issue, it affects every single theme out there which is not adjusted to the new method.

I opened this issue to bring it to attention of the maintainer. For now you can simply use the fix from the link above.

**Comment by dsifford** [comment]
I'll look into this later this afternoon and push out a fix.

In the meantime, can someone comment a section of code that I can copy paste to reproduce? (screenshots are helpful, but written code is easier!)

Thanks!

**Comment by dsifford** [comment]
Update: still waiting for [my distro's package repository](https://www.archlinux.org/packages/community/x86_64/code/) to push out the update for vscode. Can't repro til that happens. Should be in the next day or two.

**Comment by sergiz** [comment]
> 
> 
> I'll look into this later this afternoon and push out a fix.
> 
> In the meantime, can someone comment a section of code that I can copy paste to reproduce? (screenshots are helpful, but written code is easier!)
> 
> Thanks!

Basically any JS code.

`console.log()`

already has wrong highlighting.

**Comment by dsifford** [comment]
Got it, thanks!

**Comment by DoanVanThuong** [comment]
`editor.semanticHighlighting.enabled": false`

it work for me

**Comment by EduardoAraujoB** [comment]
![Captura de tela de 2020-03-11 14-02-14](https://user-images.githubusercontent.com/42449213/76446380-c12e1d80-63a5-11ea-8f6f-8ab408b1f8da.png)
the test colors broke with this new vscode update

**Comment by dsifford** [comment]
Still waiting for my distro to push the vscode update, but when that happens I'll have a fix pushed out shortly after.

**Comment by EduardoAraujoB** [comment]
Ok, thanks

**Comment by EduardoAraujoB** [comment]
> `editor.semanticHighlighting.enabled": false`
> 
> it work for me

worked for me too

**Comment by dsifford** [comment]
Just don't forget to re-enable that when the fix gets pushed out. That's gonna be a killer feature!

**Comment by EduardoAraujoB** [comment]
Nice, I will re-enable it later

**Comment by JimmyMultani** [comment]
Hey @dsifford, has your distro pushed an update yet?

**Comment by dsifford** [comment]
Ugh, no! Getting pretty annoyed and might have to download insiders or something in the meantime.

**Comment by dsifford** [comment]
@JimmyMultani Update: just compiled it myself and i got the update finally... I'll look into these issues later this evening or tomorrow at the latest.

**Comment by dsifford** [comment]
Okay, so here's the bummer... It doesn't appear that this is actually fixable beyond turning off semantic highlighting right now.

I quickly combed through some of the issues checking syntax groups and they are all being highlighted correctly, when identified correctly. The issue is, however, that there is some inconsistencies with identification (using react as an example: class components vs function components are highlighted differently).

So, for now, I'll keep this open, but there's not much more I can do until the issue is sorted out upstream.

**Comment by JimmyMultani** [comment]
Yeah, that is a bummer. Thanks for looking into it, @dsifford.

**Comment by JimmyMultani** [comment]
FYI @dsifford, the latest VSCode update now defaults semantic highlighting to `false`. So the issue is no longer present.

**Comment by atomiks** [comment]
After enabling the semantic highlighting in the latest patch release, it works much better than it did before, thank you team 🙏

**Comment by sergiz** [comment]
So this can then be turned into a feature request to make Dracula theme support semantic highlighting.

**Comment by dsifford** [comment]
@sergiz It's on my radar. Plan on deep diving [this](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#as-a-theme-author-do-i-need-to-change-my-theme-to-make-it-work-with-semantic-highlighting) when i get some extra time (possibly this weekend).

**Comment by sergiz** [comment]
I guess that this has already been resolved.
