### ISSUE TITLE
minimap color enhancement

### ISSUE THREAD

**Issue by leandrocunha** [dracula/visual-studio-code#133]
Hi guys,
What do you think to update minimap color to keep consistency of colors theme. Look the picture:

![minimap](https://user-images.githubusercontent.com/1820920/76301073-fd864e80-62bd-11ea-8ce9-47ef266ef994.jpg)

**Comment by dsifford** [comment]
Not sure I like this change. I'd prefer the minimap to not get in the way and with the purple, it becomes a bit too distracting.

**Comment by leandrocunha** [comment]
@dsifford Good point and I agree, but the first behavior is like the default sample, in other words minimap will be out of way (without colors distractions) till you interact with him, pointing mouse over him and clicking to scroll
