### ISSUE TITLE
Rendered whitespace in selection hard to read

### ISSUE THREAD

**Issue by beeb** [dracula/visual-studio-code#134]
When displaying whitespace characters in the selected code via `editor.renderWhitespace: selection` (which is the new default, by the way), the characters are hard to see. Pictured here is Python source code.

Dracula:
![image](https://user-images.githubusercontent.com/703631/76302347-198aef80-62c0-11ea-9236-283e82e5cf62.png)

Dracula Soft:
![image](https://user-images.githubusercontent.com/703631/76301991-8baf0480-62bf-11ea-8976-c4113c847816.png)

Not sure how feasible it would be to update `editorWhitespace.foreground` to add some contrast without it looking ugly when unselected.

**Comment by dsifford** [comment]
Open to suggestions you might have, but this is sort of an unfortunate result of how vscode layers their highlights. 

See https://github.com/dracula/visual-studio-code/issues/61#issuecomment-346242336

(theres a few more issues where there's discussion about highlight over comments with a similar sentiment as well)

**Comment by beeb** [comment]
Is there a way to easily try different colors on my end? Or do I need to clone the repo and install a local version or something? I'm not too familiar with VSCode extensions

**Comment by dsifford** [comment]
@beeb see here: https://code.visualstudio.com/api/references/theme-color

**Comment by beeb** [comment]
Thanks! I found that `#3b3b3b` is  just about where the symbols are visible both when unselected and selected. There are possible variations in saturation that work as well, like `#3a3b3d` maybe.

<img width="404" alt="Screenshot 2020-03-11 at 07 32 38" src="https://user-images.githubusercontent.com/703631/76388933-8955b480-636a-11ea-8e8f-882e67d5f980.png">

**Comment by beeb** [comment]
Additional option: use transparency, for instance `#ffffff1f` which gives this:

<img width="421" alt="Screenshot 2020-03-11 at 07 43 21" src="https://user-images.githubusercontent.com/703631/76389659-0afa1200-636c-11ea-8d49-ccdc01fb1935.png">

**Comment by leandrocunha** [comment]
I opened a PR for this improvement, really useful suggestion

**Comment by beeb** [comment]
Fixed by https://github.com/dracula/visual-studio-code/pull/135
