### ISSUE TITLE
Font in screenshot?

### ISSUE THREAD

**Issue by Leeiio** [dracula/visual-studio-code#136]
![](https://raw.githubusercontent.com/dracula/visual-studio-code/master/screenshot.png)

I like the font in screenshot, especially the handwriting font like 'this'.

**Comment by dsifford** [comment]
Ping @cfbender

**Comment by cfbender** [comment]
Hi @Leeiio! The font is called Dank Mono. You can learn more about it and purchase it [here](https://dank.sh/)

**Comment by dsifford** [comment]
Thanks @cfbender!

**Comment by Leeiio** [comment]
Thanks :)
