### ISSUE TITLE
Again, counter-intuitive tab highlight

### ISSUE THREAD

**Issue by bkis** [dracula/visual-studio-code#137]
I came to write this issue and found a closed one from 2017 with the same problem: #21  
Maybe it got fixed and changed back later?  
Anyway, maybe it's just me, but i think the active tab should be colored similar to the editor background (and the breadcrumbs for that matter), just like everyone knows it from any other ui. This is not very helpful:  
![image](https://user-images.githubusercontent.com/9215743/76537109-957e6680-647d-11ea-8608-478563816cea.png)
I understand the idea of the pink highlighting bottom line - but unfortunately it doesn't seem to help identify the active tab without thinking about it.

**Comment by leandrocunha** [comment]
For me make sense change color of breadcrumb to fit with tabs color and not the opposite

**Comment by bkis** [comment]
Fine, yes. Whatever makes the active tab look as if it is "in the front". The darker color for inactive tabs and brighter color for active tab don't work if the area below the tabs (be it the editor or the breadcrumbs) has the same color as the inactive tabs. This visually "groups" the inactive tabs with the editor/breadcrumbs.

**Comment by dsifford** [comment]
If you feel strongly about this @bkis, feel free to open a pull request with before/after images and we can discuss it there.

**Comment by bkis** [comment]
@leandrocunha you are absolutely right. The editor already has the same color as the active tab. It's just about the breadcrumbs background.  
I created a very primitive [PR](https://github.com/dracula/visual-studio-code/pull/138). Maybe you also feel like this is an improvement. I always liked this theme but this one thing annoyed me.

**Comment by bkis** [comment]
Fixed by [PR #138](https://github.com/dracula/visual-studio-code/pull/138)
