### ISSUE TITLE
Selection, highlights, and similar terms too similar

### ISSUE THREAD

**Issue by wprater** [dracula/visual-studio-code#14]
Multiple selections or similar term selections are very hard to differentiate.  Im not able to tell how many terms Ive selected when doing multi cursor editing.

Consider identifying the different vs code selection types and differentiating between them better.

Hovering over a token

![image](https://cloud.githubusercontent.com/assets/10452/23643151/b870c044-02b4-11e7-93fc-ad805034d41c.png)

Multiple tokens selected, can you tell which? :)
![image](https://cloud.githubusercontent.com/assets/10452/23643150/b6a60332-02b4-11e7-89ec-b1d47f670cdf.png)

**Comment by dsifford** [comment]
Open to any ideas/suggestions you might have @wprater. 

On the below example, do you think just making the similar selections a bit more opaque would help? 

This is one area that I personally found to be one of the trickiest since vscode offers such a wide range of selection types.

**Comment by wprater** [comment]
Id love to help.  I think you can either use a transparent version of one of your primary colors, or add a slightly contrasting border?

do you have a list of all the selection types?

**Comment by dsifford** [comment]
Yep, list can be found starting here: https://github.com/dracula/visual-studio-code/blob/master/src/dracula.yml#L19

**Comment by dsifford** [comment]
Of note: You'll notice that some of the hex codes are 8-characters in length. The last two characters correspond to the opacity.

**Comment by dsifford** [comment]
@wprater off topic, but would you mind if I bounce some ideas off you in #12 

I've come across some consistency issues and it would be helpful to have perspectives from other Dracula theme users before deciding to go with a change or not.

**Comment by wprater** [comment]
> @wprater off topic, but would you mind if I bounce some ideas off you in #12
> 
> I've come across some consistency issues and it would be helpful to have perspectives from other Dracula theme users before deciding to go with a change or not.

sure thing!  I bounce between a couple themes, none seem to quite get it all right yet.  Material Ocean, 80s Monokai, and Dracula.

**Comment by dsifford** [comment]
Gonna close this down for now due to lack of activity. If you have any further suggestions, feel free to reopen or send a PR.
