### ISSUE TITLE
It Is Showing Me The ERROR which is discribed in attachment below

### ISSUE THREAD

**Issue by Akram-Iyaz** [dracula/visual-studio-code#141]
![Screenshot from 2020-04-04 20-12-28](https://user-images.githubusercontent.com/63152553/78453729-3513cb00-76b1-11ea-9448-474f6ae723fe.png)

**Comment by Akram-Iyaz** [comment]
Can Anybody Help me to sort out this problem?

**Comment by dsifford** [comment]
Try deleting and reinstalling the theme. Looks like you’re missing a file for some reason

**Comment by Akram-Iyaz** [comment]
> Try deleting and reinstalling the theme. Looks like you’re missing a file for some reason

Thanks

**Comment by Akram-Iyaz** [comment]
> Try deleting and reinstalling the theme. Looks like you’re missing a file for some reason

Still not resolving

**Comment by dsifford** [comment]
The `theme-dracula` directory seems suspicious. By default, the theme should be installed in a directory named similarly to `dracula-theme.theme-dracula-2.21.0`.
