### ISSUE TITLE
How to set a header color in VScode markdown

### ISSUE THREAD

**Issue by meteorsh** [dracula/visual-studio-code#142]
How to highlight this header line?
![image](https://user-images.githubusercontent.com/46078304/79087516-14630980-7d72-11ea-96fd-aa56f17ad031.png)

**Comment by dsifford** [comment]
It doesn't appear that you have the dracula theme enabled.

**Comment by meteorsh** [comment]
I did enabled the dracula theme download from market, maybe it is the theme that has been modified by others author. What I want to know is that if there is a setting.json file or not so that I can use it to change any color I want.

**Comment by dsifford** [comment]
https://code.visualstudio.com/api/references/theme-color
