### ISSUE TITLE
Semantic Highlighting

### ISSUE THREAD

**Issue by babyraging** [dracula/visual-studio-code#144]
Hello,

I was wondering if there is a plan to support the newly semantic highlighting feature.

https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

The thme looks already great by only adding these lines to the settings.json, I've been using the theme with the feature enabled for a while.
```json
"editor.tokenColorCustomizations": {
	"[Dracula]": {
		"semanticHighlighting": true
	}
}
```

Thank you.

**Comment by dsifford** [comment]
Yep, this is planned. 

I'd like to comb through the API [outlined here](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#as-a-theme-author-do-i-need-to-change-my-theme-to-make-it-work-with-semantic-highlighting) and make sure all major syntaxes look alright before flipping the switch though.

Maybe next week/weekend.

**Comment by babyraging** [comment]
Glad to hear it! I'm looking forward to it, thank you.

**Comment by donatoaguirre24** [comment]
Hey @dsifford, very happy to hear that. I only want to comment. I tried enabling syntax highlight as @babyraging shows above and I found that in JSX, props, and functions have the same color, any plane to change this??

With syntax highlight:

![image](https://user-images.githubusercontent.com/20030075/79997570-20487d00-8490-11ea-84d3-d0ca911ae6d2.png)

Without syntax highlight:

![image](https://user-images.githubusercontent.com/20030075/79997770-49690d80-8490-11ea-9ced-225d5db16596.png)

**Comment by dsifford** [comment]
@donatoaguirre24 I'd actually say that the first screenshot you provide is more aligned with the [spec](https://spec.draculatheme.com/#HtmlCssAttributeNames) than the current screenshot.

Per the spec as of right now, html attributes are colored green. It's sort of unfortunate in cases where there are lots of attributes receiving lots of functions (like your example), but for most cases I don't think it'll be that much of a problem.

If you're opinions are strong on this, I'd suggest opening an issue in the spec repo with a proposal.

**Comment by aeschli** [comment]
Happy to hear you are already on it. 

Check out the updated [Semantic Highlighting Wiki](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview) and the [Semantic Highlighting Guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) for more details and feel free to ping me in this issue if I can help.
