### ISSUE TITLE
How dracula displays color in code text

### ISSUE THREAD

**Issue by minhkien3123** [dracula/visual-studio-code#145]
Looking forward to receiving the help. Thanks a lot

**Comment by dsifford** [comment]
Can you elaborate what your issue is?

**Comment by minhkien3123** [comment]
> _Không có mô tả được cung cấp._

> Bạn có thể giải thích vấn đề của bạn l

**Comment by minhkien3123** [comment]
> Bạn có thể giải thích vấn đề của bạn là gì?

I installed but could not run, the code does not change color
