### ISSUE TITLE
Variable name highlighting

### ISSUE THREAD

**Issue by bdielman** [dracula/visual-studio-code#148]
Since enabling semantic highlighting I've noticed that the variable name for `const` is highlighted differently than for `let` or `var`. I've attached two screenshots, the first is the latest version of Dracula, the second the default dark theme for VSCode to compare. Not a big deal, but I thought it worth mentioning.

<img width="440" alt="Screen Shot 2020-04-29 at 11 55 47 AM" src="https://user-images.githubusercontent.com/94547/80627247-96fbf200-8a1d-11ea-98cb-7c1083777079.png">

<img width="441" alt="Screen Shot 2020-04-29 at 11 55 08 AM" src="https://user-images.githubusercontent.com/94547/80627260-9a8f7900-8a1d-11ea-9442-64c9be969073.png">

**Comment by dsifford** [comment]
Yeah, the semantic highlighter treats `const` variables as true constants, which is the reason for the color difference.

I'd be open to adjusting back to being the variable color on javascript (js,jsx,ts,tsx) syntaxes if we're able to target those specifically (i believe we can -- see [here](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#theming))

Feel free to open a PR if you have time to try it out.

**Comment by bdielman** [comment]
Ah, that makes sense. I'll take a look at changing it back and issuing a PR, but I'll close this issue for now. Thanks!
