### ISSUE TITLE
Remove CHANGELOG.md

### ISSUE THREAD

**Issue by zenorocha** [dracula/visual-studio-code#15]
Is there any reason why we need a `CHANGELOG.md` file since we use GitHub Releases already?

**Comment by wprater** [comment]
Is this what vs code reads in the extension panel?

**Comment by dsifford** [comment]
@wprater Correct

**Comment by zenorocha** [comment]
Hmmm, so we can really remove it

**Comment by dsifford** [comment]
@zenorocha I'm confused. What was the issue with keeping the changelog?

**Comment by zenorocha** [comment]
Sorry, there was a typo over there.

I wanted to remove because all the other repos only use GitHub Releases to communicate changes. But since VSCode needs this file, then I'm fine with keeping it here.
