### ISSUE TITLE
Cant handle @ [at] inside src=""

### ISSUE THREAD

**Issue by yandiro** [dracula/visual-studio-code#151]
Can't handle this properly:

```
 <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
```

![image](https://user-images.githubusercontent.com/27643901/81505257-49428c00-9331-11ea-9eca-82c4759471c2.png)

**Comment by dsifford** [comment]
This is a syntax issue, so I'd look into reporting this upstream, which appears to be https://github.com/textmate/html.tmbundle according to the [html syntax in the vscode repo](https://github.com/microsoft/vscode/blob/master/extensions/html/syntaxes/html.tmLanguage.json)
