### ISSUE TITLE
Follow Link box is black

### ISSUE THREAD

**Issue by Negan1911** [dracula/visual-studio-code#152]
On any case, follow link box is black:
![image](https://user-images.githubusercontent.com/3399236/81877505-a9b51180-955b-11ea-9a76-aaf68d927af0.png)

Should be something like this (VSCode default theme as example):
![image](https://user-images.githubusercontent.com/3399236/81877560-c94c3a00-955b-11ea-8799-dd0409ddd0b7.png)

Please, ignore all the sad errors on my project 😂

**Comment by dsifford** [comment]
Not sure what the exact problem is, but it appears it has something to do with the layering of those specific color codes in the terminal.

Testing with just regular foreground text doesn't seem to replicate the issue:

![image](https://user-images.githubusercontent.com/5240018/81978796-08c96380-95fa-11ea-89e6-a91909ee3fa9.png)

**Comment by giulianoAX** [comment]
same problem:
![image](https://user-images.githubusercontent.com/65334135/82020527-8c7e6100-9689-11ea-877e-89f372e83e9e.png)

**Comment by AnilSonix** [comment]
See this https://github.com/dracula/visual-studio-code/issues/154#issue-620461593

**Comment by AnilSonix** [comment]
Can override in vs code
```
"workbench.colorCustomizations": {
  "editor.hoverHighlightBackground": "#ff000080"
}
```
