### ISSUE TITLE
font color php closing tag '?>'

### ISSUE THREAD

**Issue by crThiago** [dracula/visual-studio-code#153]
I don't know if it's a bug, but when I comment the php closing tag the font color appears in blue
![image](https://user-images.githubusercontent.com/33141686/82108123-cfc8e600-9702-11ea-8726-2b41d936a7a7.png)

**Comment by dsifford** [comment]
What other extensions do you have enabled? Seems like a conflict with a different extension.

I can't reproduce this..

![image](https://user-images.githubusercontent.com/5240018/82217526-8b973a80-98e8-11ea-8984-dd983fbbd861.png)

**Comment by crThiago** [comment]
My mistake, the **Better Comments** extension is creating this blue comment
