### ISSUE TITLE
Colors don't match when function arguments (at the function's body) are created inside an object with shorthand property names

### ISSUE THREAD

**Issue by itayperry** [dracula/visual-studio-code#159]
I'll of course show an example :) 
In a regular theme if you have a function argument inside the round brackets colored in a certain shade, then the argument inside the function should be colored the same. 
The thing is, if I take the argument inside the function and wrap it with curly braces it won't happen.

### A regular theme:
![image](https://user-images.githubusercontent.com/37377389/91145510-3eccb800-e6be-11ea-807d-02d6f3bc7ace.png)
As you can see, **the color of the arguments in the round brackets is identical to there color inside the functions**, even if they are surrounded in curly braces using the `Object Property Shorthand Notation`.
### The amazing (and my favorite) Dracula theme: 
![image](https://user-images.githubusercontent.com/37377389/91145880-cd413980-e6be-11ea-8b55-5bbd28065bd8.png)

#### `GovId` and `CenterId` are not colored 😔

**Comment by dsifford** [comment]
Hi @itayperry. Glad to hear you're enjoying the theme.

What you're reporting looks to be as expected.

The reason why the colors are the same for the default dark theme is because function parameters and object properties are colored the same, which they are not for dracula.

An example of that can be seen here:

```ts
const a = 'a';
const b = 'b';

function foo({ a, b }) {
            // ^  ^ both variable.parameter scope
  return a + b;
}

foo({ a, b });
   // ^  ^ both variable.other.property scope

const foobar = {
  foo: 'foo',
//^^^ variable.other.property scope
  bar: 'bar',
//^^^ variable.other.property scope
}
```

Hope that makes sense!

**Comment by itayperry** [comment]
Yes, I guess that's it :) Do you think it'll ever change?? I just really love this theme! 🥇

**Comment by dsifford** [comment]
Object properties probably will not change.

The function parameter scoping issue would be something that would just need to be updated in https://github.com/Microsoft/TypeScript-TmLanguage

That's outside the scope of this project though, so I have no authority to make any judgment calls as to whether or not that'll happen. There's probably some technical limitations with the textmate regex scoping that makes this sort of thing particularly difficult from the syntax side.
