### ISSUE TITLE
Unable to install via git

### ISSUE THREAD

**Issue by wizeman** [dracula/visual-studio-code#16]
Your web page says:

```
Install using Git
If you are a git user, you can install the theme and keep up to date by cloning the repo:

$ git clone https://github.com/dracula/visual-studio-code.git ~/.vscode/extensions/theme-dracula
```

However, this doesn't seem to work anymore: vscode complains about a missing `theme/dracula.json` file.

**Comment by dsifford** [comment]
@wizeman Yeah, that's not correct. The theme exists as yaml (for maintainability) and needs to be built before using. I'm not sure how to edit the theme's page on the dracula site to reflect these changes (ping @zenorocha).

You can still install via git by following those steps, but you also have to do two more things:
1. `cd ~/.vscode/extensions/theme-dracula` and `npm install`.
2. `npm run build`.

**Comment by benjamreynolds** [comment]
The themes page on the dracula site is [here](https://github.com/dracula/dracula.github.io/tree/site/src/content/visual-studio-code).

**Comment by dsifford** [comment]
Thanks @benjamreynolds -- I'll send a PR later on when I get some time. 👍
