### ISSUE TITLE
Wrong color for console.log in JavaScript/TypeScript

### ISSUE THREAD

**Issue by danmcgoo** [dracula/visual-studio-code#160]
Since Visual Studio Code 1.48, the color of console.log changed as mentioned in microsoft/vscode#104616.

Here is a screenshot of the behavior before 1.48:
![image](https://user-images.githubusercontent.com/777129/92021692-6f65bf00-ed5a-11ea-8750-e88c0d086808.png)

And here is a screenshot of the behavior since 1.48:
![image](https://user-images.githubusercontent.com/777129/92021668-6543c080-ed5a-11ea-8c4c-7532af1d4c5d.png)

It seems that there is a way to fix this issue as mentioned [here](https://github.com/microsoft/vscode/issues/104616#issuecomment-681824443).

Would it be possible to integrate this fix in the Dracula theme for Visual Studio Code ?

**Comment by danmcgoo** [comment]
@dsifford So, is this issue fixed or just closed and will never be fixed ?

**Comment by dsifford** [comment]
@danmcgoo The updated color is more correct than the previous color. 

If you'd like to revert it to the old format, this is something I would suggest doing in your user settings.

**Comment by danmcgoo** [comment]
@dsifford Thank you for you reply.
