### ISSUE TITLE
Highlighting is broken

### ISSUE THREAD

**Issue by HMaker** [dracula/visual-studio-code#161]
![Dracula's highlighting](https://user-images.githubusercontent.com/23155511/92259488-9a145c80-eead-11ea-9453-9547b0fedc8b.png)
VS code version:
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic snap

It suddenly became broken, I did not change any setting. I uninstalled dracula's theme, it seems the default vscode's highlighting is also broken:

![Default highlighting](https://user-images.githubusercontent.com/23155511/92260623-933a1980-eeae-11ea-805d-4ae9f97de0b6.png)

**Comment by dsifford** [comment]
I've got to be honest. I don't see what you're seeing. What is broken?

> it seems the default vscode's highlighting is also broken:

This would lead me to believe that if there is an issue, it is upstream and not related to this project. Maybe check in the vscode repo?
