### ISSUE TITLE
Python docstring color change in Dracula Soft in version 2.22.2

### ISSUE THREAD

**Issue by ajdajd** [dracula/visual-studio-code#163]
There was a release a few hours ago and I noticed this change in Python docstring color. I am not sure if this is intended.

Theme: Dracula Soft
Left panel: 2.22.2
Right panel: 2.22.1

![image](https://user-images.githubusercontent.com/13794421/99340673-72853b80-28c3-11eb-8ca5-155e7a8b252a.png)

**Comment by dsifford** [comment]
This was intended. I discovered a bug in the build phase of the soft variant that caused some colors (namely, comments in this example) to not receive any color definition. Therefore, the scheme just defaulted back to the default dark comment color.
