### ISSUE TITLE
entity.name.type overrides

### ISSUE THREAD

**Issue by luizwhite** [dracula/visual-studio-code#164]
Why this rule is overriding for me?

<img src="https://user-images.githubusercontent.com/4944479/99426520-f3076480-28e2-11eb-9160-a03463736d18.png" width="500">

ANother theme that I have, the same rule "entity.name.type" does not override "meta.type.parameters entity.name.type"

I can't understand what's going on.

**Dracula Soft Theme**

**Comment by dsifford** [comment]
I'm not sure I understand the question. Can you elaborate a bit further?

**Comment by luizwhite** [comment]
sorry, i am not an advanced user
I was just trying to understand why the "entity.name.type" rule overrides the "meta.type.parameters entity.name.type"
I say this because the color inside TS type declaration is the same that the entity typed
![image](https://user-images.githubusercontent.com/4944479/99975836-76accf80-2d81-11eb-82be-f542ca019845.png)

But in other theme that i have, the theme has the same token rule but it dont overrides
