### ISSUE TITLE
Terminal blue is way off

### ISSUE THREAD

**Issue by geekley** [dracula/visual-studio-code#166]
Please fix the terminal blue/brightBlue colors. They're way off (in purple).
To test just do a `ls /` in bash. Folders should be blue. The purple is really confusing.
[To test all terminal colors](https://stackoverflow.com/a/30578008): `for ((i=0; i<=48; i++)); do; tput setaf "$i"; echo HELLOBASH; done`

Dracula v2.22.2
![code-dracula](https://user-images.githubusercontent.com/38332912/100018030-8dbbe380-2dba-11eb-82b8-d42a33ba428b.png)

Default Dark+
![code-default](https://user-images.githubusercontent.com/38332912/100018043-96141e80-2dba-11eb-8d94-264d60fc0a09.png)

 You might want to tweak cyan a little bit as well.

**Comment by dsifford** [comment]
This is the intended color. Terminals have the concept of `blue` and `cyan` so we chose our `blue` representation to be the dracula purple color. This is firm and will not be changing.

**Comment by geekley** [comment]
Do you have something against the blue color? :laughing: You just skipped it in your palette... why not just add one more color?
I mean... purple is not a shade of blue by any stretch of the imagination. That's like saying orange is a shade of red. Also, I'd think Dracula and bats have everything to do with blue.

Palettes are meant for mapping colors to semantics, but like you said terminals do have the concept of "blue". It's not just "choose eight arbitrary different colors for these semantics", they're supposed to correspond. Terminals are generic. Any kind of program can run in them. I gave the `ls` example (which bothers just because I'm used to blue for folders), but other programs may run where "blue" isn't a code for representing some other concept - it really means "a blue color".

Well, do whatever you want. Thankfully I can just override ansiBlue in VS Code, so I don't have to stop using the theme.
But I have to say... this is wrong. Conceptually wrong. Especially for something that's supposed to be generic and usable everywhere.

**Comment by dsifford** [comment]
You're not wrong, but this is just how it's defined in the spec. 

You're free to make your case [here](https://github.com/dracula/spec) if you feel strongly about the change.

I will say, however, in your example I would argue having `blue` represented with the purple color is much more distinct and differentiable between the `cyan` color shown. The blue and cyan there are far too close to being the same thing.

**Comment by geekley** [comment]
> The blue and cyan there are far too close to being the same thing.

Agree. Ideally, the contrast (hue angle diff) in magenta/purple/blue/sky/cyan would be somewhat consistent, or at least as much as the palette allows it.
