### ISSUE TITLE
[Vue] broken slot highlighting

### ISSUE THREAD

**Issue by wenfangdu** [dracula/visual-studio-code#167]
Broken behavior:
![code](https://user-images.githubusercontent.com/28700378/103615492-a694e880-4f65-11eb-9ee1-3ace0d289af4.png)

Normal behavior:
![ss](https://user-images.githubusercontent.com/28700378/103615593-ce844c00-4f65-11eb-9bad-aaf35bd5d3c3.png)

**Comment by dsifford** [comment]
This looks like it's probably an issue that should be opened with the vue syntax provider you're using.
