### ISSUE TITLE
Latest GitHub Releases don't have a .vsix asset

### ISSUE THREAD

**Issue by jankeromnes** [dracula/visual-studio-code#168]
The two latest GitHub Releases don't have a `.vsix` asset.

Could you please upload one for https://github.com/dracula/visual-studio-code/releases/tag/v2.22.3? 🙏

**Comment by dsifford** [comment]
Looks like there's a weird bug going on in the build action. I'll look into that later.

In the meantime, I uploaded a vsix to the latest release manually.
