### ISSUE TITLE
Workbench theming support

### ISSUE THREAD

**Issue by beefsack** [dracula/visual-studio-code#17]
With the release of 1.11, there are a number of new elements which can be styled, though they note that the new theme format isn't finalised and is likely to change so supporting it early may result in some wasted effort.

Will be great to have the status bar more tightly integrated into the theme.

https://code.visualstudio.com/updates/v1_11#_preview-workbench-theming

**Comment by dsifford** [comment]
@beefsack Cool! I'm still waiting for my package manager to update the vscode package, but I'll see if I can get out an experimental version of that soon after that happens.

Looks fairly easy to implement (at least for now)

**Comment by rajasimon** [comment]
Wo. This will be interesting.

**Comment by dsifford** [comment]
@rajasimon Likely will be able to get to this later this evening. If not, definitely tomorrow. 👍

**Comment by dsifford** [comment]
@beefsack @rajasimon Just pushed out `v1.9.0`. Let me know your thoughts after you get a chance to play around with it. 

Thanks 👍

**Comment by beefsack** [comment]
Oh wow, that's awesome 😄 It's a huge amount better having the lairy status bar softened a lot, that was a big distraction for me previously.

The only think I'm noting at the moment is that the file text for inactive tabs feels a little faint, but it may be a non-issue as it's not like it's unreadable, I'll give myself some time to adjust to the changes and see.  Huge improvement though, looks fantastic.

**Comment by dsifford** [comment]
@beefsack Sounds great. Feel free to send in a PR with any suggested changes.

Relevant lines for the UI are here: https://github.com/dracula/visual-studio-code/blob/master/src/dracula.yml#L24-L87

**Comment by rajasimon** [comment]
I really like this theme thanks for the good work.

**Comment by rajasimon** [comment]
If it's good to have slight differentiate between Activity Bar and Side Bar. 

**Before**

![screenshot from 2017-04-07 15-50-39](https://cloud.githubusercontent.com/assets/6974101/24796310/25337236-1baa-11e7-8f32-60783b106940.png)

**After**
![screenshot from 2017-04-07 15-51-39](https://cloud.githubusercontent.com/assets/6974101/24796335/35694c66-1baa-11e7-9531-b86b92e4cf14.png)

I made above changes using developer console but I have no idea where should I add border-right in the yml file

**Comment by dsifford** [comment]
@rajasimon Good point. 

I don't think there's currently a way to give a right border to the sidebar. I can adjust the background to be slightly different than the editor background color however.

Right now, the UI theming is a lot of guesswork. It's not documented anywhere yet.

**Comment by beefsack** [comment]
@dsifford I think it might be worth closing this ticket as you've already (impressively) added support for the undocumented API. We can open new tickets down the road if the IDE changes or if any of us have PRs going forward.
