### ISSUE TITLE
Function argument variables no longer changing color within function

### ISSUE THREAD

**Issue by TestedDog** [dracula/visual-studio-code#170]
I recently noticed that some of my colors are not behaving like they did just a few hours ago.

Previously, they looked something like this:
![image](https://user-images.githubusercontent.com/17938868/109752050-b0297e00-7bad-11eb-87e1-0aa95620360d.png)
Notice how "props" is orange and italicized both in the function and as an argument.

Currently, my code looks like this:
![image](https://user-images.githubusercontent.com/17938868/109752160-e404a380-7bad-11eb-8266-74cf4874ea6f.png)
In this code, "oldState" should be orange and italicized within the function as well, but it isn't.

I can't think of anything that I have done that would affect changing colors. I have also tried uninstalling/reinstalling the theme and restarting VS Code with no success. Additionally, many of my constants that used to be purple are now white as well. Thanks!

Small update: I have tried testing this feature in other, unrelated code and it doesn't seem to be working there either. I seriously doubt there was an update that changed this so I figure it must be on my end. Additionally, nothing is showing up in VS Code outline. I have no idea if that relevant or not but couldn't hurt to share.

P.S. I would be more than happy to include more screenshots or information as needed.

**Comment by dsifford** [comment]
@TestedDog It sounds like you likely disabled semantic highlighting in vscode.

Can you check to see if `editor.semanticHighlighting.enabled` is set to `true`?

**Comment by TestedDog** [comment]
Looks like it was set to `configuredByTheme` by default. I tried setting it to `true` with no success.

**Comment by dsifford** [comment]
I see. 

Yeah, what's odd is the "before" pic you attached is actually not how the theme is set up to work. Only function parameters should be highlighted in the orange color.

The reason that I thought it might have been semantic highlighting is that in that condition, the editor becomes aware that the `props` variable is a parameter and can retain the parameter highlighting.

With default highlighting, the editor is not "smart" in that same way so all variable-like things are just highlighted in the foreground color.

**Comment by TestedDog** [comment]
Interesting. It was the first picture I found of what I had sort of looked like before. Apologies for any confusion. Regardless, "oldState", which is definitely an argument was highlighted before. Is there anything else I can try?

**Comment by dsifford** [comment]
Unless I'm misunderstanding you, it looks like from your example `oldState` is highlighted correctly in the argument scope.

In the other places where `oldState` is being used, it isn't in a function argument scope so it highlights it as it would any variable.

**Comment by TestedDog** [comment]
I see what you mean. I just went to look to find another example to make sure I'm not seeing things (and because I am unable to reproduce it) and sure enough, nothing I found looked like what I would swear I used to have. Seeing as this is apparently not a feature, is there any way I can add this manually on my end? (I read a post a little while ago where someone was recommended to make a change locally). I really liked it actually. While writing I did notice one last thing.

![image](https://user-images.githubusercontent.com/17938868/109880802-612f2780-7c45-11eb-96ef-6b4990e7337c.png)

The variable `embed` used to be purple and continued to be every time it was used. However, as you said, this is not a feature. Maybe I really am seeing things. Anyway, thank you, and please let me know if there are any local changes I can make.

**Comment by dsifford** [comment]
That's odd. I just double checked my vscode editor and in an empty js file, my const variables look like this.

![image](https://user-images.githubusercontent.com/5240018/110006694-f682f800-7ce7-11eb-8e69-19aceaf97063.png)

Have you tried reinstalling the extension?

**Comment by TestedDog** [comment]
I've just tried reinstalling both the theme and VS Code and unfortunately, my code still looks the same.

![image](https://user-images.githubusercontent.com/17938868/110025557-85e6d600-7cfd-11eb-85c6-983a496aadfb.png)

**Comment by dsifford** [comment]
Hm... Can you try nuking your user settings?

**Comment by TestedDog** [comment]
Do you mind telling me how? I have to admit to being quite new at this.

**Comment by dsifford** [comment]
Yeah, it looks like your editor just isn't using semantic highlighting. 

> Do you mind telling me how? I have to admit to being quite new at this.

You should have a `settings.json` file saved [in one of these locations](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations) (depending on platform). Just rename that file something else and then reload vscode.

**Comment by TestedDog** [comment]
Just tried that. My settings now exclusively consist of:

![image](https://user-images.githubusercontent.com/17938868/110027194-ad3ea280-7cff-11eb-8bdb-259caf386a9d.png)

Unfortunately, still no change.

**Comment by dsifford** [comment]
Hm... very strange indeed. 

Is your friend also on a Windows machine?

**Comment by TestedDog** [comment]
> Is your friend also on a Windows machine?

Yep. And I think I mentioned earlier that this used to work and somehow changed at some point. I cannot even begin to think what I could have done that would cause this. Not to mention, it should have been fixed by a fresh install. However, I was signed into my Microsoft account. I might give it another try being signed out, so it doesn't import any old settings.

**Comment by TestedDog** [comment]
Success! I logged out of my account as well as deleted any lasting VS Code data. Not sure what did the trick.

![image](https://user-images.githubusercontent.com/17938868/110029393-69996800-7d02-11eb-9e3b-0304724d235b.png)

**Comment by dsifford** [comment]
Glad to hear. Closing this for now. Open it back up if you notice any other oddities.

**Comment by TestedDog** [comment]
Found the problem. Apparently, I was viewing my code in Plaintext instead of JavasScript and when it is in plaintext, semantic highlighting does not appear to work. Figured I'd mention it.
