### ISSUE TITLE
Add secondary button styles

### ISSUE THREAD

**Issue by misolori** [dracula/visual-studio-code#176]
VS Code will start using the secondary button style in custom dialogs. These are visible on Windows and on the web (i.e. Codespaces). To see this:

1. [Install Insiders 1.56](https://builds.code.visualstudio.com/builds/insider)
2. Set `"window.dialogStyle": "custom",` in your user settings
3. Try to close an unsaved file that will prompt the dialog below

![image](https://user-images.githubusercontent.com/35271042/116309010-17eae800-a75d-11eb-8f8f-25a9cfcadd43.png)

Since this is a newer color token, you'll need to add a few tokens:

- `button.secondaryBackground`
- `button.secondaryForeground`
- `button.secondaryHoverBackground`

**Comment by dsifford** [comment]
Thanks @misolori!

Are you aware if this is planned to roll out on the next stable release?

**Comment by misolori** [comment]
Yes, this is planned to be in the next release that should ship next week.
