### ISSUE TITLE
HTML tag's style property is not colored correctly

### ISSUE THREAD

**Issue by kathleenmiranda** [dracula/visual-studio-code#177]
Hello, I'm using VS Code version 1.55.2 and noticed that the style property in HTML files is not following the color scheme.
![image](https://user-images.githubusercontent.com/59895389/116487019-58358d80-a865-11eb-9de0-f08a2c0fd9c7.png)

In the screenshot above, you can see that only the first quotation marks are yellow, while the rest is white, including the closing quotation marks. This is happening in both color themes, Dracula and Dracula Soft. Is this behavior correct?

**Comment by dsifford** [comment]
This is likely an issue with the syntax. To verify, see if a similar issue occurs with any other theme.

**Comment by kathleenmiranda** [comment]
I changed the theme and it only seems to happen on the Dracula themes.

Here is the screenshot when using Atom One Dark Theme:
![image](https://user-images.githubusercontent.com/59895389/116579458-c96a5480-a8e8-11eb-949f-877a5a0394d5.png)

Here it is with the default VS Code theme:
![image](https://user-images.githubusercontent.com/59895389/116579504-d424e980-a8e8-11eb-9676-8bde2108d71d.png)

And here is the Electron Color theme:
![image](https://user-images.githubusercontent.com/59895389/116580328-a42a1600-a8e9-11eb-94dc-eb06cba6a801.png)

**Comment by dsifford** [comment]
Fixed in 252f50b35b83aa66222104d8782082f776d67c6e
