### ISSUE TITLE
The default style of search is so poorly discerned that it makes you dizzy and dizzy

### ISSUE THREAD

**Issue by faydanube** [dracula/visual-studio-code#179]
![对比度](https://user-images.githubusercontent.com/8817046/115340188-d3999e00-a1d8-11eb-9934-7d7a4b3ae8f2.png)

**Comment by Anselmoo** [comment]
Also via _global search_ a little bit difficult for `*.py`-files

### Dracula:
<img width="392" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/3a9d1530-7f1d-4f37-856a-9c5bd4475283">

### Dracula soft:

<img width="397" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/2152ad62-91d6-4502-9cb3-f48fc3f3f4e8">
