### ISSUE TITLE
highlight in search and in selection look identical

### ISSUE THREAD

**Issue by nguyenhuumy** [dracula/visual-studio-code#18]
Here I select the word `something` but cannot differentiate the selection in the search result.

<img width="769" alt="screen shot 2017-04-07 at 4 01 11 pm" src="https://cloud.githubusercontent.com/assets/5990387/24791435/a7c1d3ee-1bac-11e7-819b-51ab830d7729.png">

**Comment by rajasimon** [comment]
It's differentiate with lighter colour. I attached the correct image. Do you have any suggestion to improve this behaviour?

![screenshot from 2017-04-07 15-04-33](https://cloud.githubusercontent.com/assets/6974101/24794834/be9e38d0-1ba4-11e7-85c0-46ec9a9a9627.png)

**Comment by dsifford** [comment]
@nguyenhuumy @rajasimon This might be something that we'll have to just live with until Microsoft documents the available textmate scopes. The latest update undid a bunch of useful scopes that we had previously (I assume they've just been renamed, but I'm not sure what those names are for now).
