### ISSUE TITLE
Python not properly colored 

### ISSUE THREAD

**Issue by rbrasco** [dracula/visual-studio-code#180]
theme: Dracula v2.22.3
Colors do not appear on:
- `def`
- `return`
- variables
- strings
![Screenshot from 2021-06-07 15-06-43](https://user-images.githubusercontent.com/38588779/121021808-0ce69700-c7a2-11eb-8b83-9d31a42fbed8.png)

But, on top of the same file:
![Screenshot from 2021-06-07 15-10-57](https://user-images.githubusercontent.com/38588779/121022468-a2822680-c7a2-11eb-90aa-9f1236d16f19.png)

**Comment by dsifford** [comment]
Does this issue happen with other color themes? If so, this is going to be an issue with the syntax, not the theme.

**Comment by rbrasco** [comment]
This issue happens with other color themes indeed.

**Comment by rbrasco** [comment]
I found the problem, conflicting pluggins for python!
