### ISSUE TITLE
[FR] update Quick Pick & suggest widget colors

### ISSUE THREAD

**Issue by wenfangdu** [dracula/visual-studio-code#181]
[VSCode `v1.57.0` release introduced a few new color tokens that control focus foreground](https://code.visualstudio.com/updates/v1_57#_updated-quick-pick-suggest-widget-colors):

- `list.focusHighlightForeground`
- `quickInputList.focusForeground`
- `editorSuggestWidget.selectedForeground`

Which need to be reflected in the VSCode Dracula theme as well.

The current default `editorSuggestWidget.selectedForeground` `#f8f8f2` doesn't look good for Dracula:

![image](https://user-images.githubusercontent.com/28700378/122659656-bb300a80-d1ac-11eb-82c1-90dba11c40bd.png)

**Comment by dsifford** [comment]
I'm not seeing what you're seeing

![image](https://user-images.githubusercontent.com/5240018/127886241-449d63e0-adb0-4943-98ea-474bb8b59b1d.png)

**Comment by wenfangdu** [comment]
@dsifford What version of VSCode are you using? The setting to unset the icon color isn't published yet:

- https://github.com/microsoft/vscode/issues/128062

Similar issue to mine:

- https://github.com/microsoft/vscode/issues/125998

**Comment by wenfangdu** [comment]
@dsifford Which version of VSCode are you using? The setting to unset the icon color isn't published yet:

- https://github.com/microsoft/vscode/issues/128062

Similar issue to mine:

- https://github.com/microsoft/vscode/issues/125998

**Comment by dsifford** [comment]
My screenshot was taken using `v1.58.0`

**Comment by wenfangdu** [comment]
@dsifford Strange, upgrading to `v1.59.0` fixed this issue for me, but it's 100% reproducible for `v1.57.x` using `v2.23.1` Dracula.

**Comment by wenfangdu** [comment]
@dsifford I found out it was fixed by https://github.com/microsoft/vscode/pull/126288#issue-669835650 in v1.58. `list.activeSelectionIconForeground` was enabled for all themes in v1.57, therefore caused this issue.
