### ISSUE TITLE
[Bug] Multiple selections aren't rendered correctly

### ISSUE THREAD

**Issue by wenfangdu** [dracula/visual-studio-code#184]
Default dark theme config:

```json
{
  "workbench.colorCustomizations": {
    "editor.selectionBackground": "#f008"
  }
}
```

![2021-07-04 10_07_42](https://user-images.githubusercontent.com/28700378/124370979-b5a7e980-dcaf-11eb-8f83-8d9f633b8f3b.gif)
Dracula config:

```json
{
  "workbench.colorCustomizations": {
    "[Dracula]": {
      "editor.selectionBackground": "#bd93f980"
    }
  }
}
```

![2021-07-04 10_11_25](https://user-images.githubusercontent.com/28700378/124371018-4b437900-dcb0-11eb-87d9-a17d8343293d.gif)

**Comment by wenfangdu** [comment]
@dsifford Please see https://github.com/microsoft/vscode/issues/127948#issuecomment-902540074:

> The problem is that the Dracula theme defines the following color:
>
> ```
> "editor.selectionHighlightBackground": "#424450",
> ```
>
> This color is not using transparency, so the selection highlights are being rendered on top of the selection. This is an oversight with the theme. Please open an issue against the theme at https://github.com/dracula/visual-studio-code.
>
> A workaround would be to customize that color to add some transparency to it:
>
> ```
> "workbench.colorCustomizations": {
>         "[Dracula]": {
>             "editor.selectionBackground": "#bd93f980",
>             "editor.selectionHighlightBackground": "#59595e88"
>         }
>     },
> ```
>
> ![image](https://user-images.githubusercontent.com/5047891/130207242-f70359ab-ae48-49ea-bd4c-d82a5a584280.png)

**Comment by dsifford** [comment]
@wenfangdu Try setting `editor.selectionHighlightBackground` to `#8BE9FD30` and let me know if you are satisfied with that.

**Comment by wenfangdu** [comment]
@dsifford Can you give a color suggestion for `editor.selectionBackground` as well, so I can check them in comparison.

**Comment by wenfangdu** [comment]
This is the `editor.selectionBackground` & `editor.selectionHighlightBackground` comparison in the default dark theme:

![image](https://user-images.githubusercontent.com/28700378/130531814-f88104c5-9d7c-4dd6-a649-d4df74d9e58e.png)

This is the `editor.selectionBackground` & `editor.selectionHighlightBackground` comparison in the Dracula theme:

![image](https://user-images.githubusercontent.com/28700378/130531950-e4aba5d2-7ad5-4b0f-bdd6-e3d9cfc2f1e4.png)

In the default dark theme, `editor.selectionBackground` is more obvious, whereas in the Dracula theme, `editor.selectionHighlightBackground` is more obvious, I think we should adjust both `editor.selectionBackground` & `editor.selectionHighlightBackground` and make `editor.selectionBackground` more obvious.

**Comment by wenfangdu** [comment]
@luxonauta Please reopen this issue, since #253 has been reverted.

**Comment by wenfangdu** [comment]
@dsifford @luxonauta @zenorocha Please reopen this issue, since #253 has been reverted.
