### ISSUE TITLE
Bezel around terminal

### ISSUE THREAD

**Issue by gfyre** [dracula/visual-studio-code#185]
There is a bezel around the terminal window when a new session of VSCode is created.

<img width="1096" alt="Screenshot 2021-07-04 at 12 04 51 PM" src="https://user-images.githubusercontent.com/23535062/124375596-abdab200-dcc0-11eb-9497-d8eb79d8a337.png">
<img width="826" alt="Screenshot 2021-07-04 at 12 05 00 PM" src="https://user-images.githubusercontent.com/23535062/124375598-aed5a280-dcc0-11eb-8522-21533412d1a9.png">

The temporary fix is to create a new terminal session which does not seem to face a similar issue. Once a new session is created, the older one can be shut.

<img width="822" alt="Screenshot 2021-07-04 at 12 05 13 PM" src="https://user-images.githubusercontent.com/23535062/124375600-b006cf80-dcc0-11eb-9d89-6669dc646a33.png">

**Comment by dsifford** [comment]
@gfyre I'm unable to reproduce this.

Does this also happen with shells other than zsh?

**Comment by gfyre** [comment]
Hey @dsifford, yes it does. Here's the screenshot for TMUX
<img width="1170" alt="Screenshot 2021-08-03 at 4 19 39 PM" src="https://user-images.githubusercontent.com/23535062/128003524-39f982e3-c634-4d34-b8f8-7245458ca5cf.png">

and here's one of Bash

<img width="1172" alt="Screenshot 2021-08-03 at 4 19 13 PM" src="https://user-images.githubusercontent.com/23535062/128003476-ea8c7c2f-a477-4896-b8dc-0595178e8e36.png">

**Comment by dsifford** [comment]
@gfyre I trust that it is happening to you, but I'm still not able to repro on my end.

Any more details that would allow me to repro would be appreciated.
