### ISSUE TITLE
Python: Undefined functions/variables/methods/properties have the same color with the defined ones

### ISSUE THREAD

**Issue by tchar** [dracula/visual-studio-code#186]
Hey.

Check the screenshot below between the default theme from Vs Code and Dracula.
Dracula colors all the missing variables/props/methods/functions with the same corresponding color as the non missing ones.

VS Code theme puts the missing ones in white (different color than non missing).

Its easier to distinguish when you make a typo or something.

See `dracula.get()` vs `dracula.no_get()`, `dracula.value` vs `dracula.no_value`, `func()` vs `no_func()` and `a = a + 1` vs `b = b + 1`

![dracula-vscode](https://user-images.githubusercontent.com/6424426/125815489-74654956-5f6b-4b51-a0dd-f7dc76f0bbad.jpg)

Cheers!
EDIT: Ignore the retarded instantiation of `Dracula` class

**Comment by tchar** [comment]
@dsifford Hmm that's weird

Just to confirm.
- The default theme is Dark+ (default dark)
- Python extension (`ms-python.python`) is installed
- You saved the file once (idk but for new files doesn't work on me either unless I save them at least once)
- Linter doesn't matter

I guess the coloring comes from the python extension

**Comment by dsifford** [comment]
Still not able to repro after following your steps.

![image](https://user-images.githubusercontent.com/5240018/128248190-a43a265a-a56f-4804-85bb-b125dc7319a7.png)

**Comment by tchar** [comment]
Huh? that's weird

I disabled all my extensions and left only the python extension open. Indeed it doesn't color them on its own. What colors them is pylance (`ms-python.vscode-pylance`) which at least in my case was installed when I installed the python extension (`ms-python.python`).

You can disable pylance and the python extension still works and produces your screenshot. With pylance and a restart I get
this

![pylance](https://user-images.githubusercontent.com/6424426/128251608-201106e0-c549-42ae-bfff-43f6771f6fc8.png)

Sorry for this whole situation its confusing to me too. If you still can't reproduce it you can close the issue I guess.

Thank you for helping me.

**Comment by dsifford** [comment]
Is the pylance server only available with insiders using proposed apis? Can't get it to work on my regular vscode build.

**Comment by tchar** [comment]
In case these matter:
- VSCodeVersion: 1.59.0 (commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8) from [snapcraft](https://snapcraft.io/code)
- OS: Ubuntu 20.04.2 LTS
- Python: 3.8.10

(But same behavior with Windows 10, Python 3.9 from Windows Store)

No I don't think so. To be honest I was using settings sync so I was not sure if any settings were picked up from Windows (in case I registered in some insiders program). I setup a new user and it just works out of the box. As far as I can remember this is the default behavior from vs code and I thought it's the norm.

Completely new OS user (first run of vs code)

https://user-images.githubusercontent.com/6424426/128553201-2c47b90d-f298-4f34-b6b9-ca10910a0844.mp4

After installing the plugin these extensions where installed (`code --list-extensions`)
-ms-python.python
-ms-python.vscode-pylance
-ms-toolsai.jupyter

Is your python extension maybe too old and not shipped with the syntax highlighting? You can try reinstalling it

**Comment by dsifford** [comment]
@tchar This is great info. Appreciate the detail here.

I'll check into this in a bit and ping back with an update. Might be later this evening/tomorrow.

**Comment by tchar** [comment]
Sure, take your time. If you need the exact versions of Windows, Python and Vscode form my windows installation, I can log it and get them for you.

Cheers!
