### ISSUE TITLE
Dart Extension : Ruined The Font Color

### ISSUE THREAD

**Issue by nyomanartha** [dracula/visual-studio-code#187]
Hello Good Sir,

I am currently learning Dart languages, and I'm in Love with Dracula theme.
However, I just noticed that, while enabling the Dart Extension in Visual Studio, the color of the font in Dracula theme seems to be ruined. I have tried to restart it several times, and even install and uninstall VS Code and Dracula themes, however nothing works.

Here is the video recording of what happened.

https://user-images.githubusercontent.com/8662441/128106758-26c897f4-7549-4f9e-aad0-ae49607445b8.mp4

Do you think, there is any solution for this problem?
Thank You very much!

**Comment by dsifford** [comment]
@nyomanartha I'm not able to repro this behavior on my end...

![image](https://user-images.githubusercontent.com/5240018/128249078-701901d4-02e1-4350-915d-1cc0873e62b6.png)

There's a chance that there's another extension that you have installed that is creating this issue. Try disabling other extensions to rule that out.

**Comment by nyomanartha** [comment]
Thank you for the feedback :)

The strange thing is that, i have tried disabling all other extensions, and it only happened when Dart Extension is enabled.

Anyhow, I have found the solution for this problem by disabling semanticHighlighting inside the dart extension setting in the "settings.json" by adding this text

`"editor.semanticHighlighting.enabled": false`


![image](https://user-images.githubusercontent.com/8662441/128280192-366cd3c1-605b-41f6-a2fa-088ae1d7a477.png)

Thank you very much!

**Comment by dsifford** [comment]
That's quite strange because I had semantic highlighting enabled when I looked into this and still didn't notice a problem.

**Comment by ameenbadri7** [comment]
> Thank you for the feedback :)
> 
> The strange thing is that, i have tried disabling all other extensions, and it only happened when Dart Extension is enabled.
> 
> Anyhow, I have found the solution for this problem by disabling semanticHighlighting inside the dart extension setting in the "settings.json" by adding this text
> 
> `"editor.semanticHighlighting.enabled": false`
> 
> ![image](https://user-images.githubusercontent.com/8662441/128280192-366cd3c1-605b-41f6-a2fa-088ae1d7a477.png)
> 
> Thank you very much!

you saved my live..
