### ISSUE TITLE
Python: function calls not highlighted when semantic highlighting is disabled

### ISSUE THREAD

**Issue by thinety** [dracula/visual-studio-code#188]
I believe 73c38e45f797daadfbad9e5e038b8d46f87969fe introduced some unwanted behavior.

With semantic highlighting enabled:
![image](https://user-images.githubusercontent.com/51510921/129109824-91518aba-1ccc-4900-ada5-e53ffee20fe1.png)
![image](https://user-images.githubusercontent.com/51510921/129109759-ce177a56-6824-4f95-9a0e-52cb59f11b31.png)
Both are expected.

Now, with semantic highlighting disabled:
![image](https://user-images.githubusercontent.com/51510921/129109944-f5e8ec22-f2e5-4508-b09c-055be8e1953e.png)
![image](https://user-images.githubusercontent.com/51510921/129109984-6fce6e4d-16e3-48f6-8002-9c997a63875e.png)
In this last image, even though `foo` is defined, the function call is not highlighted.

I confirmed `v2.23.0` (d8ebd9fa51816bbe586f1b1a96686dd3788e9ee8) does not present this behavior.

**Comment by dsifford** [comment]
Thoughts @tchar?

**Comment by tchar** [comment]
Hey @dsifford.

Although I have no idea about the available keywords you can use when defining colors and if you can programmatically check about any highlighting/language server being used this is the default behavior for all color schemes I have tested with language highligting disabled.

Here are some samples with language server disabled:

Dark+ (default VSCode)
![darkplus_foo](https://user-images.githubusercontent.com/6424426/129157418-93cb40f9-459e-4517-9757-de22c48b4bc8.png)
Monokai
![monokai_foo](https://user-images.githubusercontent.com/6424426/129157432-58a2cce9-d414-4564-b3ae-136ae5354cc5.png)
Here is Github theme from the marketplace (not installed by default)
![github_foo](https://user-images.githubusercontent.com/6424426/129158120-c7474d86-db1f-46e2-ae25-9177691b7b38.png)
![githublight_foo](https://user-images.githubusercontent.com/6424426/129158142-de5d06eb-4b3e-4fad-904b-b39378489f6a.png)

**Comment by HMaker** [comment]
@tchar can't `meta.function-call.generic` be colored? I had this issue for months and fixed now with profile settings:
```json
    "editor.tokenColorCustomizations": {
      "textMateRules": [
          {
              "scope": "meta.function-call.generic",
              "settings": {
                  "foreground":"#50fa76"
              }
          }
      ]
    },
```

**Comment by dsifford** [comment]
I'm going to go ahead and close this as it seems that only 1 way can work and not both and I'd prefer to better support users who use semantic highlighter.

**Comment by ZodiacFRA** [comment]
Sorry to comment on this closed issue, but I'm having the same problem when using Dracula (2.24.2) for Python (I'm on Fedora)

I do have `"editor.semanticHighlighting.enabled": true` in my settings so to my understanding I should have function calls colored in green? 

Any ideas? :)

**Comment by renat-murtazin** [comment]
> @tchar can't `meta.function-call.generic` be colored? I had this issue for months and fixed now with profile settings:
> 
> ```json
>     "editor.tokenColorCustomizations": {
>       "textMateRules": [
>           {
>               "scope": "meta.function-call.generic",
>               "settings": {
>                   "foreground":"#50fa76"
>               }
>           }
>       ]
>     },
> ```

This is a working solution! Thanks a lot!
