### ISSUE TITLE
Workbench theming - terrible contrast on debug menu

### ISSUE THREAD

**Issue by 23doors** [dracula/visual-studio-code#19]
![image](https://cloud.githubusercontent.com/assets/1051101/24803180/b06c4b52-1baa-11e7-8116-e55932f453ec.png)

Especially "play" sign due to lack of border looks pretty terrible. Screenshot doesn't give it full justice to be honest.

Otherwise very good job on workbench theming! Although I would also suggest slightly better contrast on file tabs.

**Comment by dsifford** [comment]
@23doors Yikes, you're right. That's pretty bad!

I'll get that fixed.
