### ISSUE TITLE
Replace screenshots with non-subpixel-renderedversions

### ISSUE THREAD

**Issue by GeoffMaciolek** [dracula/visual-studio-code#192]
(There will be a pull-request momentarily; wanting to reference this issue # in my commit.)

## The Problem 

The **excellent** [screenshot](screenshot.png) provided here has a minor issue - the computer that rendered it is set to use [sub-pixel rendering](https://en.wikipedia.org/wiki/Subpixel_rendering) - this is fine when viewed at normal sizes on typical desktop LCD displays, but does not scale well - see the attached images. There are "funky color fringes" around the edges. Is it important? Not really, but, I've done a replacement screenshot that addresses this.

### Subpixel Rendered (the current screenshot)

![screenshot-subpixel](https://user-images.githubusercontent.com/10995633/131201821-c8c92e48-e087-4506-be98-d422e3eaf43d.png)

### Non-subpixel Rendered (the current screenshot)

![screenshot-nosubpixel](https://user-images.githubusercontent.com/10995633/131201817-63624067-584d-447a-bccb-ac4a18d6fac6.png)

### Future Options

It may make sense to try to switch our systems to the no-subpixel-rendering mode before taking screenshots! Also, is there a guide, beyond [this discussion](https://github.com/dracula/dracula-theme/discussions/444?sort=top)?

### Creation Notes

Font appears to be Fira Code, size 16 - at least on my system! Please do double check that everything looks good, though!

**Comment by dsifford** [comment]
Fair enough! Making the change sounds fine to me.

> Font appears to be Fira Code, size 16 - at least on my system! Please do double check that everything looks good, though!

The font used was Monaco, but that doesn't really matter to me. Any mono font is fine for demo purposes.
