### ISSUE TITLE
colors for bracket pairs in vscode 1.60.0

### ISSUE THREAD

**Issue by jd-0001** [dracula/visual-studio-code#196]
Since vscode update 1.60.0 (https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization) enabling native brack pair colorization it messes up the Dracula colors for brackets.

![Screenshot from 2021-09-03 17-01-38](https://user-images.githubusercontent.com/47495003/131998662-824908aa-f2c2-4f8b-a6d9-e71ad47f79f8.png)

Notice that inappropriate blue color

**Comment by dsifford** [comment]
Added in #195
