### ISSUE TITLE
Error color of terminal (vs code)

### ISSUE THREAD

**Issue by DanyaSh** [dracula/visual-studio-code#199]
What's wrong with the color of my terminal?
How to fix it?
Please! Help!
I really like this theme, but work in terminal very difficult.

![изображение](https://user-images.githubusercontent.com/10911390/136375448-17ae64f6-cfa9-42a7-b624-ca96c8783eb8.png)

**Comment by DanyaSh** [comment]
Can you give me settings.json like Dracula Soft please?

For example:
"workbench.colorCustomizations" : {
        // "terminal.foreground" : "#00FD61",
        // "terminal.background" : "#383737",
        "terminal.background":"#131212",
        "terminal.foreground":"#dddad6",
        "terminal.ansiBlack":"#1D2021",
        "terminal.ansiBrightBlack":"#665C54",
        "terminal.ansiBrightBlue":"#0D6678",
        "terminal.ansiBrightCyan":"#8BA59B",
        "terminal.ansiBrightGreen":"#237e02",
        "terminal.ansiBrightMagenta":"#8F4673",
        "terminal.ansiBrightRed":"#FB543F",
        "terminal.ansiBrightWhite":"#FDF4C1",
        "terminal.ansiBrightYellow":"#FAC03B",
        // "terminal.ansiBlue":"#00a1f9",
        "terminal.ansiBlue":"#131212",
        "terminal.ansiCyan":"#8BA59B",
        "terminal.ansiGreen":"#95C085",
        "terminal.ansiMagenta":"#8F4673",
        "terminal.ansiRed":"#FB543F",
        // "terminal.ansiWhite":"#A89984",
        "terminal.ansiYellow":"#FAC03B"
    },

**Comment by Grezor** [comment]
@DanyaSh It does this to me sometimes in the terminal too, I put Oh My Zsh Themes on my vscode terminal. 
I don't know, if it can create problems. I don't know, if it can cause problems, but I put it in and it works again.

**Comment by jaigouk** [comment]
here is what I am using for dracula in my vscode 

```
"workbench.colorCustomizations": {
    "[Dracula Soft]": {
      "sideBar.background": "#343746",
      "sideBar.border": "#bf9eee",
      "sideBarSectionHeader.background": "#343746",
      "activityBar.background": "#343746",
      "tab.activeBackground": "#343746",
      "editor.background": "#343746",
      "panel.background": "#343746",
      "editor.selectionBackground": "#6272a4",
      "editor.selectionHighlightBackground": "#44475a",
      "editor.findMatchBackground": "#6272a4",
      "editor.findMatchHighlightBackground": "#6272a4"
    },
    // https://glitchbone.github.io/vscode-base16-term/#/dracula
    "terminal.background":"#282936",
    "terminal.foreground":"#E9E9F4",
    "terminalCursor.background":"#E9E9F4",
    "terminalCursor.foreground":"#E9E9F4",
    "terminal.ansiBlack":"#282936",
    "terminal.ansiBlue":"#62D6E8",
    "terminal.ansiBrightBlack":"#626483",
    "terminal.ansiBrightBlue":"#62D6E8",
    "terminal.ansiBrightCyan":"#A1EFE4",
    "terminal.ansiBrightGreen":"#EBFF87",
    "terminal.ansiBrightMagenta":"#B45BCF",
    "terminal.ansiBrightRed":"#EA51B2",
    "terminal.ansiBrightWhite":"#F7F7FB",
    "terminal.ansiBrightYellow":"#00F769",
    "terminal.ansiCyan":"#A1EFE4",
    "terminal.ansiGreen":"#EBFF87",
    "terminal.ansiMagenta":"#B45BCF",
    "terminal.ansiRed":"#EA51B2",
    "terminal.ansiWhite":"#E9E9F4",
    "terminal.ansiYellow":"#00F769"
  },
```
