### ISSUE TITLE
Inconsistent bottom bar color

### ISSUE THREAD

**Issue by 23doors** [dracula/visual-studio-code#20]
Dunno if this is a bug in new workbench theming or if there is some missing property, but when I simply open a new window (File->New Window) I get as expected this in bottom bar:
![image](https://cloud.githubusercontent.com/assets/1051101/25067301/325d21dc-223f-11e7-9f28-2be1d964f907.png)

But when I open a directory (File->Open->dir), bottom bar looks like this:
![image](https://cloud.githubusercontent.com/assets/1051101/25067308/4fae560c-223f-11e7-9eb8-4884fc23622a.png)

**Comment by dsifford** [comment]
@23doors Thanks for pointing that out! Fix has been pushed out.
