### ISSUE TITLE
Log colors

### ISSUE THREAD

**Issue by brccabral** [dracula/visual-studio-code#200]
Hi,
When opening a log file the colors of WARNING are red and ERROR are yellow. I am more the opposite type, I like warn yellow and error red.
I had to make changes in the global settings, but it would be nice to have Dracula to handle these colors.

![log_colors](https://user-images.githubusercontent.com/130455/140988844-9f24af9e-0a9c-4a24-b0f6-aaf933a9ebed.png)

Thanks,
Bruno

**Comment by dsifford** [comment]
I agree with your suggestion. That does seem strange that it was implemented that way. Feel free to open a PR for this.
