### ISSUE TITLE
JSX constants are white

### ISSUE THREAD

**Issue by bralandealmeida** [dracula/visual-studio-code#202]
Hi, my constants in JS and JSX files are white and before they were purple like in the theme example. Could they let me know if there might be a configuration error?

Thank you for any help.

![code](https://user-images.githubusercontent.com/47180618/143146444-c6708a6f-2e9f-418f-a8f7-8bbb65498753.png)

**Comment by dsifford** [comment]
Check to see if you have `editor.semanticHighlighting.enabled` set to true in your configuration.

**Comment by bralandealmeida** [comment]
Thanks. That solved the problem.
