### ISSUE TITLE
SIdepanel border 

### ISSUE THREAD

**Issue by kylegoines** [dracula/visual-studio-code#209]
Just noticed i seem to be missing the side bar and panel borders of search and explorer, i was able to re-add them in my settings.json

```
    "workbench.colorCustomizations":{
        "sideBar.border" : "#bd93f9", 
 
    },
````

**Comment by dsifford** [comment]
Thanks for the report. 

This is by design. By all means add the customization in your `settings.json` though if you like this better :+1:

**Comment by kylegoines** [comment]
sorry i dont want to nitpick but wanted to just mention that an official UI image uses the sidebar border color
![Screen Shot 2022-03-21 at 10 33 13 AM](https://user-images.githubusercontent.com/2029565/159283874-182dccce-c5b2-4964-95dc-fe27d7359b71.png)
 that can be found here: https://draculatheme.com/ui
