### ISSUE TITLE
Counterintuitive tab highlight in 1.10.0

### ISSUE THREAD

**Issue by DanielRamosAcosta** [dracula/visual-studio-code#21]
⚠️ This is just an opinion, I know dracula has fixed colors.

With the current theme it's hard to see wich tab is selected:
![current theme](https://cloud.githubusercontent.com/assets/11427028/25099654/22209256-23a5-11e7-8ea6-80451d0de496.png)

I think that something like this is more intuitive(not necessarily this):

![alt theme](https://cloud.githubusercontent.com/assets/11427028/25099738/7085efc2-23a5-11e7-9696-2018dd97841e.png)

Is more seamless and uniform:

![alt theme with tab highlighted](https://cloud.githubusercontent.com/assets/11427028/25099783/97cda052-23a5-11e7-929d-d852193a62fb.png)

In order to obtain those colors I used HSV color space and lower down the V.

**Comment by dsifford** [comment]
@DanielRamosAcosta Opinions are very welcome!

Did you mock up your images using the theme files or is it a photoshop? If it's the former, care to send a PR?

**Comment by DanielRamosAcosta** [comment]
This is my config in VS Code! I'll do a PR 😄
