### ISSUE TITLE
Selected text can't seen on folded element

### ISSUE THREAD

**Issue by sametsafak** [dracula/visual-studio-code#210]
Hi,

When I try to select something on a folded element, I can't see if it's selected or not.

In screenshot, I just select multiple lines to make it visible to you, but if I want to select some attributes in one line (like class name 123) on folded element, I just can't see if it's selected it or not.

<img width="227" alt="Screen Shot 2022-02-10 at 21 13 44" src="https://user-images.githubusercontent.com/1429542/153470517-f0c221b5-c6d2-42d5-a2bf-58fe31154475.png">

**Comment by himhimlo** [comment]
Agree, I also use code fold all the days the issue is a bit annoying.

**Comment by zhulien-ivanov** [comment]
This is an extremely annoying issue which makes the theme basically unusable in large codebases using VS Code. Any plan on addressing it?
