### ISSUE TITLE
Improve background color for sidebar

### ISSUE THREAD

**Issue by golopot** [dracula/visual-studio-code#211]
The background color looks better if it is changed to the average color for activity bar and editor.

```
  "workbench.colorCustomizations": {
    "sideBar.background": "#2e313f"
  }
```

Before:
<img width="1335" alt="Screen Shot 2022-02-16 at 11 36 20 AM" src="https://user-images.githubusercontent.com/16285118/154191634-2796062f-845b-44b9-a767-f92fd2c1e9e8.png">

After:
<img width="1335" alt="Screen Shot 2022-02-16 at 11 35 47 AM" src="https://user-images.githubusercontent.com/16285118/154191662-03be5a8b-5dcc-46cc-b7ad-0e5129dffae0.png">

**Comment by golopot** [comment]
I got it worked after I disabled all extensions and preferences. Thanks!

**Comment by charmingpark** [comment]
i luv customized theme too ;)
