### ISSUE TITLE
Defeito tema Dracula com o plugin css peek 

### ISSUE THREAD

**Issue by pinheiro-neto** [dracula/visual-studio-code#213]
<p> 
Tem um grande defeito na visualização do plugin css peek deixando o código embaçado, onde ele fica quase ilegível  </p>

![peek](https://user-images.githubusercontent.com/74797032/157558476-b325d549-2d51-424d-9ed0-4224748ae5d1.PNG)

**Comment by dsifford** [comment]
I'm sorry, I don't understand what you're asking for/reporting here. If you're able to translate what you're reporting to english, feel free to reopen and elaborate further.
