### ISSUE TITLE
Colors of the Dracula Theme changed after update of VScode

### ISSUE THREAD

**Issue by marnixhoh** [dracula/visual-studio-code#216]
<img width="748" alt="image" src="https://user-images.githubusercontent.com/47228669/167247088-3110b51b-a853-4d5e-953a-9b37c1c8aa95.png">

The colors of the Dracula Theme suddenly changed for me after updating to the latest version of VScode (1.67.0).

As can be seen in the screenshot (a React file), the curly brackets of the props are now `green`, whereas they used to be `red`. The same is true for the curly brackets used for the conditional rendering of `DateContainer`. Also the parentheses of function calls are now `orange`, they used to be `white`.

There is also inconsistency. In the `DayPickerSingleDateController` component, the curly brackets of the props are `green`, but these are `purple` for the `BookingItems` component.

These are just some of the color changes (there are more). Any help would be greatly appreciated!

What I have tried so far:
- restarting VScode
- disabling and enabling the Dracula Theme plugin

**Comment by rostyslav-a-smartgamma** [comment]
Hello, same, after VS code update now colors my PHP code are different... terrible

**Comment by marnixhoh** [comment]
@rostyslav-a-smartgamma Thank you so much for sharing a link to that issue. I lost hours trying to figure out what caused this...
