### ISSUE TITLE
Parameter not highlighting as should

### ISSUE THREAD

**Issue by giulianosrebuli** [dracula/visual-studio-code#219]
Hi everyone.
I use Dracula for a few months now, but this week some highlighting just went missing and i can't tell why. This is a example code:

![image](https://user-images.githubusercontent.com/44322465/173834578-f2f0ecd2-87ea-48b7-aad4-8f1351ce77a6.png)

My main concern is to the parameter _(*buffer)_ which should be orange inside the function as well, just like it's shown in the readme:

![image](https://user-images.githubusercontent.com/44322465/173834780-30fca8a5-79fb-4d5a-aa6d-32de6bba8f3b.png)

The struct name is a little strange too, if i'm not mistaken it was blue before, now it's plain. 

At first i thought it was becausa my project was starting to be too large, but on a single-file project happens the same

Can somebody help me understand what is going on and how can i solve it? 
Already tried to uninstall e reinstall Dracula on VSCode, also tried to uninstall and reinstall VSCode itself, but nothing works. Any help would be largely appreciated.

**Comment by giulianosrebuli** [comment]
My semantic highlighting is on for all color themes.

I am using C, the comparison was made because it used to look like that before, i.e. the parameter would still be orange in all its uses inside the function

**Comment by dsifford** [comment]
> the parameter would still be orange in all its uses inside the function

This is something that is 100% controlled by semantic highlighting so I would triple check that you do indeed have it enabled.

**Comment by giulianosrebuli** [comment]
![image](https://user-images.githubusercontent.com/44322465/173864444-c885ee03-d9b0-46fc-b115-0db987b11ba3.png)
 unless i'm doing something wrong here, it is enabled
