### ISSUE TITLE
Go Highlight

### ISSUE THREAD

**Issue by qxxiao** [dracula/visual-studio-code#220]
Hi,
For Go language highlighting, function call tokens are in the same color as the **type**.

![image](https://user-images.githubusercontent.com/43007848/174409598-843700fb-c3b5-4f24-b5b7-96c5b4c88774.png)
And function arguments seem to be a known issue in known_issues.md

**Comment by dzdiscoveryzone** [comment]
Same here. I briefly had this working in VSCode out of nowhere and then it stopped working again randomly. I've tried overrides and can't seem to get this to work. On the contrast for JetBrains GoLand this works perfectly.

**Comment by dzdiscoveryzone** [comment]
> This is not issue of Dracula, but issue of gopls. Add this line `"gopls": {"ui.semanticTokens": true},` to your `settings.json`
> 
> `CTRL+Shift+P` -> `Open User settings (JSON)`

Thank you @arxeiss! This resolved it for me
