### ISSUE TITLE
Peek view background color should be BGLight instead of BG?

### ISSUE THREAD

**Issue by himhimlo** [dracula/visual-studio-code#226]
Does any body agree that the background color of the peek view should be BGLight instead of BG?
Now:
![image](https://user-images.githubusercontent.com/3815971/196591796-d8436319-85aa-4e8e-ae23-9b16862c668b.png)
Should be:
![image](https://user-images.githubusercontent.com/3815971/196591721-03d1edbb-a027-42fe-a160-ab3da5cd144c.png)

**Comment by luxonauta** [comment]
(#253)
