### ISSUE TITLE
Cursor (caret) color

### ISSUE THREAD

**Issue by ajitid** [dracula/visual-studio-code#23]
[Feature Request]
Don't you think that giving fuchsia color to cursor will make it more Dracula type?
If yes, then please give it in the next release! 😍

**Comment by dsifford** [comment]
@ajitid Because it's non-standard and to some may be visually striking, I can't add that to the theme itself.

......but!

You can enable the pink cursor for yourself by adding the following to your User Settings:

```json
"workbench.experimental.colorCustomizations": {
    "editorCursor": "#ff79c6"
}
```

Hope that helps! Thanks for the feedback! 😄

**Comment by ajitid** [comment]
I've done that experimental color customisation already. Thanks!
