### ISSUE TITLE
JSX-tags are white and textMateRules doesn't apply

### ISSUE THREAD

**Issue by Jose-DallAsta-008** [dracula/visual-studio-code#231]
Custom created JSX-TAGS are not with color
the problem is: they are white

Already tried changing the textmate scopes detailed in the printscreen
The language is typescript with react, on nextjs framework.

![image](https://user-images.githubusercontent.com/100225790/210411731-4c5b5249-9a30-4fff-a16e-196723d24a06.png)

What i already tried:
```typescript
  "editor.tokenColorCustomizations": {
    "[Dracula At Night]": {
      "textMateRules": [
        {
          "name": "React component name colorization",
          "scope": [
            "support.class.component.tsx",
            "entity.name.tag.tsx",
            "meta.tag.tsx",
            "meta.jsx.children.tsx",
            "meta.tag.without-attributes.tsx",
            "meta.block.tsx",
            "meta.function.expression.tsx",
            "meta.export.default.tsx",
            "source.tsx",
            "entity.name.tag",
            "support.class.component.tsx"
          ],
          "settings": {
            "foreground": "#991818"
            // "foreground": "#ff0000"
          }
        }
      ]
    },
    "comments": "#21cc69"
  },
```  

Output of code above:
![image](https://user-images.githubusercontent.com/100225790/210411305-4c2d1e54-4867-47fc-8669-a28bcce94b87.png)

Other themes work fine and the tag has color, but dracula at night is just better, could someone help me out into adding color to it? 
Thanks in advance

**Comment by annetters** [comment]
Bump for this. Also saw that "const" was pink in the theme preview image but white in real life.

**Comment by dsifford** [comment]
@Jose-DallAsta-008 I'm sorry for the delay here. But did you say the theme you are using is "Dracula at night"? If so, this is not that theme.

**Comment by luxonauta** [comment]
(#253)
