### ISSUE TITLE
Markdown strikethrough font style/color is missing.

### ISSUE THREAD

**Issue by DamianPereira** [dracula/visual-studio-code#232]
This is how it looks currently:

<img width="727" alt="Screenshot 2023-03-27 at 07 04 35" src="https://user-images.githubusercontent.com/17646954/227910959-fc368075-7fd9-4f50-9e0d-2b0605a2e177.png">

This is how the default vscode theme looks:
<img width="727" alt="Screenshot 2023-03-27 at 07 05 15" src="https://user-images.githubusercontent.com/17646954/227911007-7ef9eb23-4cf7-43f9-9965-8e01a6404981.png">

This is from my local version with modifications:
<img width="727" alt="Screenshot 2023-03-27 at 07 03 29" src="https://user-images.githubusercontent.com/17646954/227911062-a146dcfd-2b96-44f1-9f6a-ed07946a365f.png">

Not sure about the color, but please review it/check it out!

**Comment by luxonauta** [comment]
(#253)
