### ISSUE TITLE
Extension removed from marketplace?

### ISSUE THREAD

**Issue by alexferreiraofc** [dracula/visual-studio-code#236]
Dracula Official removed from marketplace?

![image](https://github.com/dracula/visual-studio-code/assets/74845734/bd5600b6-88fa-4f6c-85a9-b2934b269101)

**Comment by dsifford** [comment]
Thanks for reporting. This is being tracked here: https://github.com/dracula/dracula-theme/issues/878

Don't download the copy extension. We're not yet aware if there's been a leak of deploy keys or not and we cannot vouch for the content of that clone.
