### ISSUE TITLE
Extension missing

### ISSUE THREAD

**Issue by mbd-s** [dracula/visual-studio-code#237]
Dracula Official can no longer be found when searching Visual Studio Code extensions. (A copycat theme with the same name still shows up.) Also, the [marketplace page](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula) for the extension results in a 404. Was the theme removed?

<img width="1047" alt="Screenshot of 404 error on VS Code marketplace page for Dracula Official" src="https://github.com/dracula/visual-studio-code/assets/13588399/1755afdd-6821-4ab1-b308-0a6423088043">

<img width="559" alt="Screenshot of VS Code extension search for Dracula Official" src="https://github.com/dracula/visual-studio-code/assets/13588399/9dab9915-38e9-4764-b7c0-414bc2016a1f">

**Comment by dsifford** [comment]
Thanks for reporting. This is being tracked here: https://github.com/dracula/dracula-theme/issues/878

Don't download the copy extension. We're not yet aware if there's been a leak of deploy keys or not and we cannot vouch for the content of that clone.
