### ISSUE TITLE
Expand selection to quotes

### ISSUE THREAD

**Issue by ajitid** [dracula/visual-studio-code#24]
VS Code has this nice expand selection feature. While expanding selection, Dracula include quotes (maybe because it gives same color to the quotes) but other themes like Nord and Material Theme (Mattia's one) does not. Everytime when I need to clear out anything inside a quote and replace it with something, putting those quotes again gives me another step. Can you fix that?
![drac](https://cloud.githubusercontent.com/assets/26769888/25374689/ff2de466-29bb-11e7-9230-5e5ff7f0443d.gif)

**Comment by dsifford** [comment]
@ajitid Very strange! Not totally sure why that would be happening, but I'll look into it. Thanks for reporting👍

**Comment by dsifford** [comment]
@ajitid Yep, this looks like it's a bug with vscode itself.

Just tried changing the colors of the quotes and it fixes the issue. Could you open an issue with vscode about this?

Scopes of interest:
- `punctuation.definition.string.begin`
- `punctuation.definition.string.end`

When set to a different color than `string`, it expands correctly. When set to the same color, it does not.

Thanks a bunch! I'm sure the VSCode guys and gals will also appreciate hearing about this 😄

**Comment by ajitid** [comment]
Can you please tell me what exactly I needed to write in issue? Actually I'm totally new to GitHub and and everything. 😅 So can you please report this issue rather than me doing it. Thanks!

**Comment by ajitid** [comment]
Okay I'm putting this issue to VS Code. Will you change the color of quotes in next Dracula update or have I need to wait for VS code team to make changes?

**Comment by dsifford** [comment]
Thanks! Let's hold off until we hear back from VSCode.

**Comment by ajitid** [comment]
They just marked it as a duplicate and closed the issue. The issue for which they marked this one as a duplicate is open for one year. Now what?
