### ISSUE TITLE
Unclear active tab

### ISSUE THREAD

**Issue by gauntface** [dracula/visual-studio-code#240]
I love the theme, however I often find myself getting confused with what the active tab is.

![Screenshot from 2023-08-25 13-45-57](https://github.com/dracula/visual-studio-code/assets/139760/2abf005e-771a-44a1-9d74-179206bbb648)

Changing the active tab border to the bottom makes a big different:

![Screenshot from 2023-08-25 13-55-49](https://github.com/dracula/visual-studio-code/assets/139760/ddabebc8-341f-4d3e-ae5b-48174164180c)

Changing the bg to a light color is an extra step:

![Screenshot from 2023-08-25 13-56-16](https://github.com/dracula/visual-studio-code/assets/139760/eac0c2ca-5bc0-461c-ab4b-f0c9001a1bb2)

Is there any interest in making this change (I'm happy to raise a PR if so)?

NOTE: If you want to test this out quickly on your vscode, you can add the following to your settings.json:

```json
"workbench.colorCustomizations": {
  "tab.activeBorder": "#FF79C6",
  "tab.activeBackground": "#343746",
}
```

**Comment by luxonauta** [comment]
(#253)
