### ISSUE TITLE
Color Change in Git Diff mode

### ISSUE THREAD

**Issue by Anselmoo** [dracula/visual-studio-code#242]
I am wondering if it will be technically possible and make sense to change the ***diff git colors*** of VSCode

<img width="379" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/ddff2c1f-77a3-4a4b-b0c5-906383634b52">

to the proposed colors for:

- **Green**  <img width="25" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/756ac1da-430d-475d-9918-db313d602859">
- **Red** <img width="27" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/02b087fa-252c-45b6-b5b0-d8e8eb7a5c9d">
- 
See also:

-  #223
- https://draculatheme.com/contribute

**Comment by dsifford** [comment]
Not sure I understand the question here. What are you asking for specifically? What are the diff colors set at right now?

**Comment by Anselmoo** [comment]
Dear @dsifford 
Thank you very much for your quick answer, and sorry for the lack of clarity.

If you have unstaged changes, VSCode shows this as differences in the source control menu  (<img width="30" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/061f818e-3a97-4086-b81e-943efca65492">) like:

<img width="132" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/a34f3630-d3fe-4e18-bfa2-ca9f63f7c3d9">


however comparing 

#### with Kimbie Dark

<img width="133" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/c51ed713-f7c6-4e29-8244-b9734696920c">

#### with Monakai 
<img width="127" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/c45c4936-75aa-4a84-8c1d-197f4e8c4154">


It appears to me that the color scheme of Dracula is not very noticeable, even if it has already been specified.

https://github.com/dracula/visual-studio-code/blob/e475d548db27773fa0004b252c0a4701f187fb7e/src/dracula.yml#L258C1-L270

<img width="408" alt="image" src="https://github.com/dracula/visual-studio-code/assets/13209783/70c49ce5-e5f0-4899-96b7-d46fadde8b45">

What are your thoughts?

**Comment by dsifford** [comment]
I don't find it personally very difficult to differentiate, but I'm biased here because I'm the one who originally set it 😅

If you have any specific suggestions here, feel free to let me know or open a PR.

That said.. Since the theme has gotten to a critical mass of users (~6MM installs), I try to not introduce any jarring changes if I can avoid it so as to not rock the boat too much with those who have gotten used to things as they are.

**Comment by Anselmoo** [comment]
Thx, consistency is the overall target, I will take a look and may set a draft, not a PR. 


> That said.. Since the theme has gotten to a critical mass of users (~6MM installs), I try to not introduce any jarring changes if I can avoid it so as to not rock the boat too much with those who have gotten used to things as they are.

I cannot agree more ...

**Comment by luxonauta** [comment]
(#253)
