### ISSUE TITLE
Syntax Highlighting not working properly for JS/TS

### ISSUE THREAD

**Issue by Fazla-GroM** [dracula/visual-studio-code#245]
As of latest VSCode update syntax highlighting is not working properly (at least for me).
Im using Dracula Pro but the same behavior can be observed on Dracula.
When I switch back to default themes (dark modern, etc..) everything works as expected.

**VsCode info:**
```
Version: 1.86.1
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:57.920Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

**Dracula version(not pro)**
`v2.24.3`

**VSCode settings**
```json
{
    "workbench.iconTheme": "vscode-icons",
    "workbench.startupEditor": "none",
    "workbench.fontAliasing": "antialiased",
    "workbench.tree.renderIndentGuides": "always",
    "workbench.tree.enableStickyScroll": true,
    //terminal stuff
    "terminal.integrated.fontFamily": "'Cascadia Code PL', Menlo, Monaco, 'Courier New', monospace",
    //editor stuff
    "editor.stickyScroll.enabled": true,
    "editor.fontSize": 12,
    "editor.fontFamily": "'Cascadia Code', Menlo, Monaco, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "editor.bracketPairColorization.enabled": true,
    "editor.bracketPairColorization.independentColorPoolPerBracketType": false,
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.codeActionsOnSave": ["source.fixAll.eslint"],

    //explorer stuff
    "explorer.compactFolders": false,
    //language specific stuff
    "javascript.updateImportsOnFileMove.enabled": "always",
    "typescript.updateImportsOnFileMove.enabled": "always",

    //extension stuff
    "prettier.printWidth": 100,
    "prettier.tabWidth": 4,
    "prettier.semi": true,
    "prettier.singleQuote": false,
    "prettier.trailingComma": "es5",
    "prettier.bracketSpacing": true,
    "prettier.bracketSameLine": false,
    "prettier.arrowParens": "always",
    "prettier.htmlWhitespaceSensitivity": "css",
    "prettier.endOfLine": "lf",
    "vsicons.dontShowNewVersionMessage": true,
    "gitlens.advanced.messages": {
        "suppressGitMissingWarning": true
    },
    "security.workspace.trust.untrustedFiles": "open",

    "github.copilot.enable": {
        "*": true,
        "plaintext": true,
        "markdown": true,
        "scminput": false,
        "yaml": false,
        "typescriptreact": true,
        "typescript": true
    },

    "git.ignoreMissingGitWarning": true,
    "totalTypeScript.hideAllTips": false,
    "totalTypeScript.hideBasicTips": true,
    "totalTypeScript.hiddenTips": [
        "passing-generics-to-types",
        "record-utility-type",
        "tuple-type",
        "parameters-utility-type",
        "typeof",
        "omit-utility-type",
        "generic-slots-in-functions",
        "type-alias-with-generics",
        "type-predicate",
        "as-const",
        "conditional-type",
        "never-keyword",
        "returntype-utility-type",
        "mapped-type",
        "type-alias-with-multiple-generics",
        "keyof",
        "partial-utility-type",
        "exclude-utility-type",
        "in-operator-narrowing",
        "pick-utility-type",
        "as-const-on-object",
        "interface-with-generics",
        "nested-conditional-type",
        "required-utility-type",
        "nonnullable-utility-type",
        "infer",
        "extract-utility-type",
        "remapping-in-mapped-type",
        "bigint",
        "lowercase-utility-type",
        "uppercase-utility-type",
        "readonly-utility-type",
        "non-null-expression",
        "interface-with-multiple-generics"
    ],
    "explorer.confirmDragAndDrop": false
}
```

**Dracula screenshot**
<img width="456" alt="Screenshot 2024-02-10 at 10 42 56" src="https://github.com/dracula/visual-studio-code/assets/45801671/1fdd5412-27d0-43fc-962f-3b48be8ad023">

**Dark modern provided by vsCode**
<img width="567" alt="Screenshot 2024-02-10 at 10 43 52" src="https://github.com/dracula/visual-studio-code/assets/45801671/ea27888d-786e-4b48-8ab9-b36cefc9ce5b">

**Comment by GabrielDokov** [comment]
Have the same problem, just stop working properly

**Comment by dsifford** [comment]
Not sure I understand the issue here. What is specifically broken? The highlighting in the hover window?

Have you both tried disabling all your other extensions first to see if there's not a conflict? I'm not seeing any issues on my end.

**Comment by GabrielDokov** [comment]
Thank you for your fast response. The problem is when you declare a variable like const text = "something", the const stay white, later it was blue, also {children} in above example needs to be highlighted

**Comment by GabrielDokov** [comment]
![image](https://github.com/dracula/visual-studio-code/assets/107989651/b24c455e-7ba0-40ce-a487-7bb400a8f635)

The places where i put arrows needs to be highlighted, but they stayed white. It worked perfectly 3 days ago

**Comment by dsifford** [comment]
Looks like you might have disabled semantic highlighting. Can you check that setting to see if it is indeed enabled or not?

**Comment by GabrielDokov** [comment]
Semantic highliting is on i change it to true and to configuredByTheme but the problem stays.Upload images to see that everything is ok, it worked 2 days ago and just stop without changing settings. @dsifford 
![image](https://github.com/dracula/visual-studio-code/assets/107989651/3a87c3e7-e313-435f-866c-f36af47f6e18)
![image](https://github.com/dracula/visual-studio-code/assets/107989651/4b5090e3-cdd4-4813-bb30-d32baa4cca3a)
![image](https://github.com/dracula/visual-studio-code/assets/107989651/7720a491-889a-482e-96dd-bac474d40fd1)
![image](https://github.com/dracula/visual-studio-code/assets/107989651/d2472e40-9e38-4b4e-a6f0-d42d1567a5a2)

**Comment by Fazla-GroM** [comment]
@GabrielDokov explained everything. I also experimented with semantic highlighting on/off and it didnt change anything

**Comment by GabrielDokov** [comment]
@Fazla-GroM, @dsifford  maybe the problem comes from update of the VScode i don't know but stopped working . I have been using Dracula for 3-4 years and i have no problems since this

**Comment by Fazla-GroM** [comment]
> @Fazla-GroM, @dsifford maybe the problem comes from update of the VScode i don't know but stopped working . I have been using Dracula for 3-4 years and i have no problems since this

Yeah me too. 
I went through vsCode issues yesterday but couldn't find anything similar 🤷

**Comment by Fazla-GroM** [comment]
Also it looks generics are broken also.
If i remember correctly `SomeGeneric` and `OtherType` should also be of that light blue color.
<img width="549" alt="Screenshot 2024-02-13 at 10 30 46" src="https://github.com/dracula/visual-studio-code/assets/45801671/f64cf02d-0649-4522-a784-1176730f64a0">

**Comment by dsifford** [comment]
I cannot reproduce this on the latest (non-insiders) build of vscode on my machine. Can both of you confirm what OS you are running and also please disable all other extensions and make sure it is not a confict between extensions.

**Comment by dsifford** [comment]
Glad to hear. Any idea what extension this was so that others might be able to verify on their end?

**Comment by GabrielDokov** [comment]
We can now enjoy Dracula again 🥳

**Comment by Fazla-GroM** [comment]
Hover highlight is still not working for me though. Everything else is fine. It can be observed on photos i posted.

**Comment by lvzhenbo** [comment]
vue was updated today and the volar extension is now called vue official, which causes syntax highlighting to be disabled
![image](https://github.com/dracula/visual-studio-code/assets/32427677/7f0a4c92-42b0-4dbd-9c4f-023a6ad3a712)
![image](https://github.com/dracula/visual-studio-code/assets/32427677/5491882b-4b7d-41be-a726-79f503d8b581)

**Comment by lvzhenbo** [comment]
I deleted the comment earlier, and now I've confirmed a few things vue plugin updates are causing the syntax highlighting to be unstable
![动画 (0)](https://github.com/dracula/visual-studio-code/assets/32427677/93c02f6c-9a23-41ef-9132-c19bcf26a8a2)

**Comment by luxonauta** [comment]
(#253)
