### ISSUE TITLE
Update preview screenshot

### ISSUE THREAD

**Issue by 23doors** [dracula/visual-studio-code#25]
Current screenshot is far from the actual results and is much worse than what people are getting with this theme. As a result some people may just not give it a chance ;)

Current:
https://camo.githubusercontent.com/d695efd1815607a9056ea5817501adc0a63632ca/68747470733a2f2f64726163756c617468656d652e636f6d2f6173736574732f696d672f73637265656e73686f74732f7673636f64652e706e67

My screenshot with more or less similar code:
https://d2ppvlu71ri8gs.cloudfront.net/items/370a402J221n2H2x3S0o/Image%202017-04-28%20at%202.07.26%20PM.png

**Comment by dsifford** [comment]
Looks good to me! Could you open a PR with the fix? Thanks 😊

**Comment by 23doors** [comment]
Seems that current image is hosted here: https://draculatheme.com/assets/img/screenshots/vscode.png - is it also somewhere on github? Doesn't seem to be a part of this repo.

**Comment by dsifford** [comment]
Yes, the main location for the images is https://github.com/dracula/dracula.github.io

**Comment by 23doors** [comment]
Created PR https://github.com/dracula/dracula.github.io/pull/37

**Comment by zenorocha** [comment]
Thanks guys!

**Comment by 23doors** [comment]
FYI, seems that github is still keeping cache for their markdown readme though:
https://github.com/dracula/visual-studio-code/blob/master/README.md
dunno what's the ttl (if any) on that

**Comment by dsifford** [comment]
@23doors I'm seeing the fresh image here on my end

**Comment by 23doors** [comment]
@dsifford cool. I still see cached version here but that just means that it will refresh eventually ;)
