### ISSUE TITLE
Ruby - hash Keys & named parameter values color issue 

### ISSUE THREAD

**Issue by The-Black-Fox** [dracula/visual-studio-code#250]
=== Ruby ===

On Dracula & Dracula Pro : 

* Named parameters & default arguments should be a different color  from each other 
* Hash symbols / keys  & values should be a different color from each other 
* Named Parameters and Hash symbols  should have a different color

***
###Dracula Pro 

![images](https://screenshot.click/29-01-qpx4d-jozkn.png)

![image](https://github.com/dracula/visual-studio-code/assets/36429498/aeefcedb-ba2d-4241-b393-2ccf27e3bcc8)

*** 

### Spinel  
![image](https://github.com/dracula/visual-studio-code/assets/36429498/ce4ada66-7c8f-49a1-b8a3-549373d3b6e6)

![image](https://github.com/dracula/visual-studio-code/assets/36429498/852af832-c8d1-45fb-bb7b-533ee1be22c1)

***

### Monokai 

![image](https://github.com/dracula/visual-studio-code/assets/36429498/12a4b70c-53d4-46d5-be2f-401f8998cac3)

**Comment by The-Black-Fox** [comment]
https://github.com/Shopify/ruby-lsp

**Comment by luxonauta** [comment]
(#253)
