### ISSUE TITLE
Different color than comments for docstrings in python

### ISSUE THREAD

**Issue by Saya47** [dracula/visual-studio-code#251]
Isn't it better to have a different color for docstrings like yellow than having the same color as comments? Docstrings are more important than comments and are processed by Python, so... can we have different colors?

I know that most people want different colors, please see this:

https://stackoverflow.com/questions/76436694/in-vs-code-1-79-0-1-80-2-python-docstrings-are-colored-like-comments-how-do-i

And this:

https://stackoverflow.com/questions/76466400/why-are-docstrings-and-block-comments-suddenly-the-same-color-as-a-single-line-c

**Comment by luxonauta** [comment]
(#253)

**Comment by Saya47** [comment]
Hello can this be reopened? I did not see this resolved at all in the new version. @luxonauta
