### ISSUE TITLE
Some kind of indication of currently selected item

### ISSUE THREAD

**Issue by justin-calleja** [dracula/visual-studio-code#252]
When selecting items in recently viewed files, there's very little in the way of knowing which item is currently selected.

The white border.. is there to illustrate the issue. I added it with:

```json
	"workbench.colorCustomizations": {
		"[Dracula Pro (Van Helsing)]": {
      "contrastActiveBorder": "#fff",
      }
```

![image](https://github.com/user-attachments/assets/7b18f2b5-a349-4931-a1df-59c8623808a1)

## Edit

Found this to work well:

```json
"workbench.colorCustomizations": {
		"[Dracula Pro (Van Helsing)]": {
      "quickInputList.focusBackground": "#44475A75",
}
}
```

in global settings.json for the van helsing variation of the theme.

**Comment by luxonauta** [comment]
(#253)
