### ISSUE TITLE
Is there any problem with the latest color scheme

### ISSUE THREAD

**Issue by jacksyk** [dracula/visual-studio-code#254]
Is there any problem with the latest color scheme

**Comment by jacksyk** [comment]
![image](https://github.com/user-attachments/assets/1b512c62-46a1-496a-9151-15c1672aa624)
不期望引入的括号是红色的

**Comment by tran2001** [comment]
somethings happened to mine too, it seems like they removed the "Dracula Soft" which we're using and make it to the Pro version :(

**Comment by hologerry** [comment]
Prefer the old parentheses colors..

**Comment by Muluk-m** [comment]
I need “Dracula Soft”

**Comment by gustalima** [comment]
The button colour is a bit off ("Preview in Editor")
![image](https://github.com/user-attachments/assets/404a9c19-5b8b-42d5-a681-414b08036597)

Also, the selection highlight is really hard to notice outside of the editor (in the search pane, for example)

Unselected:
![image](https://github.com/user-attachments/assets/f766b49f-1dee-4f8b-9953-e8cf4082695b)

Selected:
![image](https://github.com/user-attachments/assets/68eefd87-ffc2-4144-8500-228ba2692a29)

**Comment by kamilraczka** [comment]
Yeah, I am not sure if it is a proper place to raise a bug or complain about accessibility but there are several other places which are hard to read e.g. the bottom bar when active:

![Screenshot 2024-07-17 at 09 29 28](https://github.com/user-attachments/assets/2d64301f-7198-478c-8c91-8d1876bc0eea)

**Comment by himhimlo** [comment]
And also the highlight of the highlighted text in UI input box is hard to see

**Comment by hologerry** [comment]
Thanks to the author’s great effort to bring this update, but I downgraded to the previous version. 😔

**Comment by gokhancvs** [comment]
![Screenshot 2024-07-17 at 11 29 48](https://github.com/user-attachments/assets/e78ad80b-618f-4e20-9246-0c16ba7c23e3)

Yes, some colors have been changed in the new version, but at least you can downgrade.

**Comment by nigiwen** [comment]
Looking forward to becoming better

**Comment by AUAboi** [comment]
Yeah a lot of th colors on the UI are messed up. Not sure why they changed it. The bracket thing and highlight color are especially really disruptive.

**Comment by timwedde** [comment]
Unwittingly updated to the newest release this morning and was quite confused by the new colors, a lot of things are hardly readable now. Came here to find a solution and luckily the downgrade still works.
Please revert this change!

**Comment by dsifford** [comment]
Sorry folks. See my comments here: https://github.com/dracula/visual-studio-code/pull/253

@luxonauta @zenorocha

**Comment by jd-solanki** [comment]
Please revert the latest changes. It's horrible 🥵

I use dracula every where please don't turn it into garbage 🙏🏻 

Thanks @dsifford for the information.

**Comment by brunovivaldodev** [comment]
Just Downgrade, please.

**Comment by lucas-subli** [comment]
New files are yellow
Brackets are Red
Edited files are soft gray and just disappear in the background

Something is very wrong, hopefully this was a mistake

**Comment by icheft** [comment]
New colors are really distracting.. using Dracula Refined as an alternative now

**Comment by brunovivaldodev** [comment]
> New colors are really distracting.. using Dracula Refined as an alternative now

Just downgrade the version change 2.25.1 to 2.24.3 or wait for the new realese

**Comment by curiosbasant** [comment]
The changes have still not reverted! 👎🏼 
Stuck on `2.24.3` 💔
