### ISSUE TITLE
I need the 'Dracula Soft' theme, and I hope it won't be removed.

### ISSUE THREAD

**Issue by Akatukiaoki** [dracula/visual-studio-code#255]
I need the 'Dracula Soft' theme, and I hope it won't be removed. The latest version doesn't have this theme, so I can only keep using the old version

**Comment by jacksyk** [comment]
How to use the old version?

**Comment by Koushik1311** [comment]
![image](https://github.com/user-attachments/assets/f5236822-be8f-4fa8-94ac-5a9d5e52f3b8)

It's too much for the eye

**Comment by andypho** [comment]
> How to use the old version?

Click on the Dracula Theme Extensions, Click on the drop down next to the Uninstall button, `Install another Version`, select 2.24.3

**Comment by jieey1140** [comment]
I had the same problem and solved it after downgrading. :cry:

**Comment by liwuxi** [comment]
yes! I need too!!!

**Comment by ahmettoguz** [comment]
Missing Dracula Soft...

**Comment by GoodbyeNJN** [comment]
It is very regrettable to update the original free features to paid features. Attracting payment should be achieved by adding more paid features instead of reducing the free features.

**Comment by romulloqueiroz** [comment]
> > How to use the old version?
> 
> Click on the Dracula Theme Extensions, Click on the drop down next to the Uninstall button, `Install another Version`, select 2.24.3

Thank you!

**Comment by raffimh** [comment]
> > How to use the old version?
> 
> Click on the Dracula Theme Extensions, Click on the drop down next to the Uninstall button, `Install another Version`, select 2.24.3

Thank you! because new version dracula ruined the theme

**Comment by kaine-bruce-dmt** [comment]
+1

**Comment by Zegfault** [comment]
+1

**Comment by edthrn** [comment]
Very un-cool to remove the "soft" theme from latest version. Your pitch includes the word "productivity", yet I lost 30 min this morning wondering why my workspace looked odd then trying to fix it back to how I like it.

Finally resolved it thank to @andypho 's [comment](https://github.com/dracula/visual-studio-code/issues/255#issuecomment-2232444016)

**Comment by dsifford** [comment]
Sorry folks. See my comments here: https://github.com/dracula/visual-studio-code/pull/253

@zenorocha @luxonauta

**Comment by PedroSoutoDev** [comment]
Hoping this gets reverted.

**Comment by luxonauta** [comment]
This change was motivated by the desire to facilitate support and align it with what we do in Dracula PRO.

We plan to introduce a Light variant in Dracula Classic (Dracula Theme), similar to what we currently have in Dracula PRO.

That said, we can revert this change and add the variant to our specifications, iterating to improve it for everyone.

We welcome PRs and feedback! 😊

**Comment by Dtesch9** [comment]
Alright, I downgraded in order to keep using `Dracula soft` which is the only set of colors that conform my eyes, the new version comes with a new set of colors that I find too strong, it would be impossible for me to code at night with this new theme.

I hope we have `Dracula soft` back on, otherwise the last good version will be my target.

**Comment by luxonauta** [comment]
https://github.com/dracula/visual-studio-code/issues/253#issuecomment-2233261721
