### ISSUE TITLE
Workbench tree indent guidelines invisible in v2.25.0

### ISSUE THREAD

**Issue by JackMyers001** [dracula/visual-studio-code#256]
I have `"workbench.tree.renderIndentGuides": "always"` set in my `settings.json`. With the latest Dracula update, indent guides are all but invisible.

**v2.25.0:**

![image](https://github.com/user-attachments/assets/4ea40538-75eb-4041-b14a-d1668a209648)

**v2.25.0 (Hover):**

![image](https://github.com/user-attachments/assets/4d868664-ec45-4451-8e73-6577824e894b)

**v2.24.3:**

![image](https://github.com/user-attachments/assets/ad0d2cb1-21bc-43d3-b64b-83560629fbf0)

_(Note the thin white line in v2.24.3)_

**Comment by dsifford** [comment]
@luxonauta @zenorocha

**Comment by luxonauta** [comment]
https://github.com/dracula/visual-studio-code/issues/253#issuecomment-2233261721
