### ISSUE TITLE
Does Dracula Pro include the old `Dracula` theme?

### ISSUE THREAD

**Issue by fz6m** [dracula/visual-studio-code#257]
I noticed the latest version of `Dracula` has only one theme with purple text. 

I have been using `Dracula` for a long time and am willing to pay for `Dracula Pro`, but I want to know if `Dracula Pro` includes the old `Dracula` themes ? I did not find the old color schemes on the `Dracula Pro` official website.

![CleanShot 2024-07-17 at 4  13 40](https://github.com/user-attachments/assets/81acb52c-9a07-45ad-94a2-a4bca1edf1d4)

(↑ old theme)

![CleanShot 2024-07-17 at 4  22 08](https://github.com/user-attachments/assets/9df4f092-642d-4442-be8e-0b2f3b57f1f7)

(↑ old color)

![CleanShot 2024-07-17 at 4  21 21](https://github.com/user-attachments/assets/38db42a1-d052-4802-bf74-8a98427ccb57)

(↑ new color)

**Comment by moong23** [comment]
want to know if there is `Dracula Soft` theme included in pro version.

**Comment by dsifford** [comment]
@luxonauta @zenorocha

**Comment by nephi-dev** [comment]
I miss dracula soft, it was a perfect balance of constrast

**Comment by luxonauta** [comment]
https://github.com/dracula/visual-studio-code/issues/253#issuecomment-2233261721

**Comment by backlands** [comment]
Just as a heads up for anyone coming here from this #253, as I did. With the now rolled back version of 1.25 being released any custom colour settings you may have had in `settings.json` would have been migrated to the "Dracula" theme namespace:

```diff
    "workbench.colorCustomizations": {
-        "[Dracula Theme]": {
+        "[Dracula]": {
            ...your custom settings...
        }
    },
```

With the rollback of that 1.25 version back to 1.24 your settings most likely were not rolled back and will no longer be applied to the theme. You will need to open your `settings.json` and change `Dracula` back to `Dracula Theme`.

It took me a while to figure this out and the contrast was way to low for me with the defaults so I use the darker `#16171e` on all background tags. How to do that is included below if it is of value to anyone else:

```json
    "workbench.colorCustomizations": {
        "[Dracula Theme]": {
            "terminal.background": "#16171e",
            "input.background": "#16171e",
            "sideBar.background": "#16171e",
            "sideBarSectionHeader.background": "#16171e",
            "activityBar.background": "#262833",
            "tab.activeBackground": "#16171e",
            "editor.background": "#16171e",
            "editorHoverWidget.background": "#16171e",
            "peekViewEditor.background": "#16171e",
            "panel.background": "#16171e",
            "breadcrumb.background": "#16171e",
        }
    }
```
