### ISSUE TITLE
Highlighted text in UI elements is not visible

### ISSUE THREAD

**Issue by janglad** [dracula/visual-studio-code#258]
Since the last updated highlighting of selected text in UI text inputs seems to have disappeared completely

Old:

https://github.com/user-attachments/assets/32c4cc4f-4683-4f2c-a43f-f82d26aaa725

New:

https://github.com/user-attachments/assets/c83ea27e-6a6f-4217-9994-40034cc4cfac

**Comment by ivanvoznyakovsky** [comment]
+1 to this. same issue when renaming files.

**Comment by dsifford** [comment]
@luxonauta @zenorocha

**Comment by luxonauta** [comment]
https://github.com/dracula/visual-studio-code/issues/253#issuecomment-2233261721
