### ISSUE TITLE
Not Working on 1.12.0

### ISSUE THREAD

**Issue by Eric-Jackson** [dracula/visual-studio-code#27]
Workbench styling isn't present in the latest release. I'm sure this is just some simple updates but I wanted to make sure it wasn't a bug on my end. 

![screen shot 2017-05-04 at 3 03 15 pm](https://cloud.githubusercontent.com/assets/1268260/25720424/d526e21e-30da-11e7-9043-93a2afc53db3.png)

**Comment by dsifford** [comment]
Thanks for the info!

Still waiting for the update to trickle down to my package manager. I'll get a fix out one that happens. 👌

**Comment by Eric-Jackson** [comment]
@dsifford Went ahead and updated this, probably will need some QA!

**Comment by 23doors** [comment]
@Eric-Jackson @dsifford thanks for a quick fix! much appreciated

**Comment by dsifford** [comment]
@23doors All credit goes to @Eric-Jackson 😄 

PS, to anybody who might be reading this: There are probably double the amount of UI selectors available to style now with the latest update, so if somebody feels like improving the UI theme, PRs are very much welcomed!
