### ISSUE TITLE
Color contrast of selection / match / search result

### ISSUE THREAD

**Issue by zyxneo** [dracula/visual-studio-code#31]
Hi!

First I like to say, that I love this theme.

It will be nice, if you can somehow improve the contrast in any "search result", even the matches by selecting words. On some monitors it is almost invisible:
![low-contrast-highliht](https://cloud.githubusercontent.com/assets/1773130/25810548/b799df4c-3410-11e7-90b8-a37ab1275dc8.jpg)
If it is visible, than still hard to decide, which is the selection itself, and which are the matches. So it will be niche to differentiate between them more.

And of course I like to have the selection in ordinary neon pink or purple color :) (probably not possible because of different languages... what a pity)

Many thanks!

**Comment by jsehull** [comment]
Agreed, I am definitely looking forward to an update on this (poor word/line highlights/recognition was one of the reasons I tried to find a different theme, but not anymore!)

The 1.15.0 has a nice border on the cursor line...maybe borders are easier across languages as well?

Keep up the good work @dsifford, I've been ecstatic looking forward to the updates on the theme I've been using for maybe 2-3 years now! Always fun to see improvements, thanks!

**Comment by dsifford** [comment]
@zyxneo @jsehull Pushing out an update here in a sec that makes small adjustments to try and improve this.

The tricky part is that VSCode doesn't allow changing the foreground color of matches so it's difficult to find colors that work with the light colors of the code.

I dialed up the intensity of the non-active selection color, dialed down the intensity of the rangeSelection color (line of active selection), and increased the intensity of the active selection's yellow color.

Hopefully that helps. If not, let me know.

**Comment by zyxneo** [comment]
Hi!

Many thanks for the quick fix. I have forget to give some proper examples, so I do it now:

So I search for word "imgs/foo":
![foobar-search](https://cloud.githubusercontent.com/assets/1773130/25896003/abdbc5a8-3582-11e7-9bb0-7b57a78db510.png)
Notice, that selection works as expected, it is fine.

Than I select the "png":
![foobar-select-png](https://cloud.githubusercontent.com/assets/1773130/25896002/abd5ce64-3582-11e7-9f5a-eb0ce4a8dfb1.png)
Notice, that things get complicated, 3 things interact: selection, search result, and line highlight. The highlights are recognizable, however hard to differentiate between them. Which is now "selection match" for example?

Than, I do a search in "quick search" for "foobar":
![foobar-quick-search](https://cloud.githubusercontent.com/assets/1773130/25896001/abd5254a-3582-11e7-9778-e2ff903817fe.png)
Notice, hat 2 things interact: search result, and quick search result. The highlights are recognizable, even the common section. It can be improved, but also fine as it is.

Than I select word "png" again, just to display all at once:
![foobar-all](https://cloud.githubusercontent.com/assets/1773130/25896000/abd33dfc-3582-11e7-99a2-9a06d4e312ee.png)
I know, nobody makes that... But that is the worst case i can have, and I sometimes actually have it.
Oh no... wait... I can even select words from the result... But anyway. Forget any more complex cases...

What I like to point, that it is hard to differentiate between selection, selection match, search result and quick search result. I like to have something like selection: blue, selection match: skyblue, search result: yellow, quick search: green. I know, extreme stupid example, but still, some more contrast.
And yes on the other hand I already see on this single example, how hard it is, highlight the word, without loosing the contrast for readability. And there are a lot of different languages with a lot of colors too... So I don't have any Idea how to make it, I just wanted to point the wish, and make a request to think about it.

And most important in my opinion is to differentiate between actual selection and matches of the selection, e.g. 2 of 3 search result, or my selection, and same word matches.

Many thanks!

**Comment by zyxneo** [comment]
And I even have forget the automatic selection of string between quotes... So there are so many things to care... Therefor, I totally understand if there is no way to make secure changes... But still, nice to have :)

**Comment by dsifford** [comment]
@zyxneo Thanks for the feedback. This is definitely a pain-point with the limited options available from VSCode.

If you'd like, you can try playing around with some combinations in your own theme by adding the following to your User Settings:

```json
{
  "workbench.colorCustomizations": {
    "editor.findMatchBackground": "<hex-color-here>",
    "editor.findMatchHighlightBackground": "<hex-color-here>",
    "editor.findRangeHighlightBackground": "<hex-color-here>",
    "editor.rangeHighlightBackground": "<hex-color-here>"
    
  }
}
```

**Comment by zyxneo** [comment]
Thank you @dsifford !

And also "Keep up the good work!"

**Comment by dsifford** [comment]
Thanks! Let me know if you come across a combination of colors that works well and I'll give it a shot 😄
