### ISSUE TITLE
Highlight search results background color makes text barely readable

### ISSUE THREAD

**Issue by nico-onmap** [dracula/visual-studio-code#34]
When doing a search in files, matches are highlighted using a yellowish background color that makes the text very difficult to read:

![vscodedracula](https://cloud.githubusercontent.com/assets/26772786/25955133/a7ae0c7a-3668-11e7-9413-7e26b4e16c1d.png)

This happens on Windows 10, VSCode 1.13.0-insider (commit 5057c95e), dracula 1.16.0

**Comment by nico-onmap** [comment]
For comparison, here is the background color used for normal (mouse) text selection:
![vscodedracula2](https://cloud.githubusercontent.com/assets/26772786/25955265/0ba84fce-3669-11e7-99f2-cea96759cba2.png)

**Comment by dsifford** [comment]
Thanks for the report. This is a dupe of #33. Closing this one in favor of that one.
