### ISSUE TITLE
Other small details

### ISSUE THREAD

**Issue by ajitid** [dracula/visual-studio-code#37]
Its about intent guides and and current line highlighting.

Intent guides can get some Dracula feel rather than any shade of black. 
Current line can also be highlighted in a more modern way by coloring whole line rather than giving thick outline to it.

Solarized Dark:
![sol dar](https://cloud.githubusercontent.com/assets/26769888/26021463/4d567fac-37ab-11e7-9e75-317d92801abe.png)

Nord:
![nord](https://cloud.githubusercontent.com/assets/26769888/26021464/51a8503a-37ab-11e7-8d45-d2c266cf9d21.png)

Material Theme:
![screenshot 199](https://cloud.githubusercontent.com/assets/26769888/26021466/5a0247ea-37ab-11e7-8e91-0d1e9a492d38.png)

Dracula:
![drac](https://cloud.githubusercontent.com/assets/26769888/26021468/6aafd85a-37ab-11e7-810c-7c6235170ee2.png)

**Comment by dsifford** [comment]
Thanks for the suggestions @ajitid 

I'm happy with the color of the indent guide. I tried playing with it in the past and it always seemed that if I adjusted it from default it either became too much of a distraction or not noticeable enough. Gonna keep as-is for now.

Re: The line highlight suggestion -- The theme actually used to highlight the line the way you're suggesting, but it became too difficult to manage hover and search highlights overlapping and creating situations that resulted in words being difficult to read at times. Also, I tend to like the square box style better, but that's just me.

Having said that, you can change it back to how it was by adding this to your user settings:

```json
{
    "workbench.colorCustomizations": {
        "editor.lineHighlightBackground": "#44475A"
    }
}
```
