### ISSUE TITLE
Support Elixir function parameters with orange color

### ISSUE THREAD

**Issue by joaoevangelista** [dracula/visual-studio-code#39]
The default color as I see for parameters on Dracula is the orange, with ruby as example:

<img width="229" alt="ruby" src="https://cloud.githubusercontent.com/assets/5256711/26214674/a0274690-3bd3-11e7-89fb-21eb98b7bc21.PNG">

But in Elixir the parameters are white: 
<img width="302" alt="ex param" src="https://cloud.githubusercontent.com/assets/5256711/26214696/b207577e-3bd3-11e7-96a1-6fd9258b988a.PNG">

Would be possible to change that to complain the "standard" ?

**Comment by joaoevangelista** [comment]
[Here](https://github.com/fr1zle/vscode-elixir/tree/master/syntaxes) is the syntax file for the languages the most popular plugin for elixir supports and the names for each match it does, I think that will be useful

**Comment by dsifford** [comment]
Thanks for the report.

Doesn't look like I'll be able to make the elixir syntax have orange params because the syntax has no scope for it. All function definition params are scoped to `source.elixir`.

The only way I'd be able to add it is if the maintainer adds the scope for it.

**Comment by joaoevangelista** [comment]
I'll see what I do for that on vscode-elixir repository. I created a small language support using the tmLanguage files that elixir team support and the parameters work.

**Comment by dsifford** [comment]
@joaoevangelista Where is that `tmLanguage` file located? Is it not part of their main language repo?

**Comment by joaoevangelista** [comment]
They are located [here](https://github.com/elixir-lang/elixir-tmbundle) under their organization. I tested it out converting directly form the bundle but I could not get better results, yes the parameters work, so the theme is ok. The real problem is that parameters works, but for vscode compat there is alot of other highlight issues witht the tmbundle, so I gave up. Then I went to check the regex for the plugin and the atom language package, both are missing the capturing group for parameters which I think they could not handle them properly. I suggest to close this issue since there is nothing to do with the theme.

**Comment by dsifford** [comment]
@joaoevangelista Is the vscode elixir repo accepting PRs? Adding scope for function params shouldn't be too difficult. Happy to help if needed.

**Comment by joaoevangelista** [comment]
They are, but as I digged in, the problem is at the regex they use to capture the params, located here (here)[https://github.com/fr1zle/vscode-elixir/blob/master/syntaxes/elixir.json#L113] I tried to apply the regex from the tmLanguage file but I got the first `(` matching, lol

**Comment by dsifford** [comment]
@joaoevangelista Hmm, I see.

I'll take a look at this in a bit. Looks like you might just be able to add a third capture group to that group that you linked to and it should work.

**Comment by dsifford** [comment]
@joaoevangelista Just spent 30 mins or so on playing around with the elixir tmLanguage file from that repo and unfortunately, the author didn't scope it in a way that will allow someone to easily add in support for the `variable.parameter` scope. There is a trove of scope overlaps and it's just an absolute nightmare to try and work through. 

The "fix" would be a refactor of that language file, but I'm guessing they won't want to do that. 

Sorry I couldn't be more helpful.

**Comment by joaoevangelista** [comment]
No problem at all! Thanks for all support! ❤️
