### ISSUE TITLE
Add soon-to-be-released UI selectors

### ISSUE THREAD

**Issue by dsifford** [dracula/visual-studio-code#41]
(Pending May 2017 Stable release)

- [x] [Parameter hints](https://github.com/Microsoft/vscode/issues/26671)
- [x] [Warning/error squiggles](https://github.com/Microsoft/vscode/pull/27053)
- [x] [`contrastBorder` overrides](https://github.com/Microsoft/vscode/issues/26530)
- [x] [`selection.background`](https://github.com/Microsoft/vscode/pull/26093)

**Comment by ajitid** [comment]
terminal.background
![dbq0db-vwaasiqd](https://user-images.githubusercontent.com/26769888/26858459-f8a7b130-4b4e-11e7-93ee-98f370ec1edb.jpg)

**Comment by ajitid** [comment]
Please remove terminal.background in next release. Thought it would look good, but it doesn't.
