### ISSUE TITLE
Color status bar highlight

### ISSUE THREAD

**Issue by ajitid** [dracula/visual-studio-code#42]
Don't know what it is called.

Steps: 
1. Press Ctrl+M to see "Tab moves focus" in status bar. This isn't colored.
2. Press Ctrl+M to hide it back again.

![capture](https://cloud.githubusercontent.com/assets/26769888/26517494/5c7efcd6-42b7-11e7-92e5-6ddf25edda84.PNG)

**Solution** is using statusBarItem.prominentBackground and statusBarItem.prominentHoverBackground

**Comment by dsifford** [comment]
Good catch. I couldn't figure out what those things were for so I didn't color them. 👍
