### ISSUE TITLE
vscode 1.13 install button

### ISSUE THREAD

**Issue by 23doors** [dracula/visual-studio-code#43]
1.13 seems to have added some new workbench theming api.
Everything seems fine (from what I experienced) except for `install` extension button.

![image](https://user-images.githubusercontent.com/1051101/26985893-c72c7444-4d45-11e7-86f4-9897e84af8a3.png)

Terrible for your eyes ;)

**Comment by dsifford** [comment]
Yiiiiiikes! Didn't notice that!

Thanks for the report.

**Comment by rajasimon** [comment]
@dsifford I can't update the extension because of the proxy. I tried to update Dracula by latest vsix but somehow it's not updating to v2.1.1

Is the latest vsix correctly updating to v2.1.1 ?

**Comment by 23doors** [comment]
@rajasimon You can download vsix manually and install it in vscode through File->Open.
https://dracula-theme.gallery.vsassets.io/_apis/public/gallery/publisher/dracula-theme/extension/theme-dracula/2.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Comment by rajasimon** [comment]
@23doors Thanks that helps
