### ISSUE TITLE
Feedback for Dracula-Soft

### ISSUE THREAD

**Issue by jaredreich** [dracula/visual-studio-code#45]
Love this theme, great work.

I'm wondering if we could perform more "softening" for Dracula-Soft. I feel like it's still very neon and painful on the eyes.

Perhaps more desaturation?

**Comment by dsifford** [comment]
Thanks @jaredreich 

I noticed this as well a few days ago when I was using the theme on a macbook. Huge difference in color intensity between the macbook screen and the screen on my daily linux machine!

I'm going to reopen #30 to track this. Care to chime in there? There's a couple other people there that were also interested in fixing up the soft variant. Maybe we can all put our heads together on it and figure out something that works better?
