### ISSUE TITLE
Recolor heads-up notification 

### ISSUE THREAD

**Issue by ajitid** [dracula/visual-studio-code#46]
VS Code 1.14 breaks colors of label and button of heads-up notification
![capture](https://user-images.githubusercontent.com/26769888/28102838-8f5210c4-66ef-11e7-8814-3562588eaad2.PNG)

New keys are in this issue: https://github.com/Microsoft/vscode/issues/28280

------------------------

Can you also revert terminal's background color? Output, Problems and Debug Console all having same bg color but Terminal having a different bg color feels strange.

If you've provided color to title bar in Mac, then update its screenshot in readme too.

**Comment by dsifford** [comment]
Thanks for the heads up (pun intended!)

I'll try to get to this soon. Going to also implement the terminal color adjustments that were suggested in https://github.com/dracula/dracula-theme/issues/232

**Comment by ajitid** [comment]
1.14 has introduced keyboard shortcuts as buttons in command palette, maybe there exists some keys for it too...

![screenshot 216](https://user-images.githubusercontent.com/26769888/28237669-9fbd9b7a-6962-11e7-804d-bc9347a14257.png)

Can you also change separator color of command palette to same as the border color which is between editor and activity bar?
