### ISSUE TITLE
Handle punctuation.definition.comment as a 'comment'

### ISSUE THREAD

**Issue by joerohde** [dracula/visual-studio-code#47]
This is similar to the puncuation addition to 'keyword'. For me the problem manifested in Javascript (Babel) with the '//' portion of the comment being white as it matched general punctuation.  Tried to do a branch/PR-Merge - alas - denied.

```
diff --git a/src/dracula.yml b/src/dracula.yml
index 9ec446a..2984ea0 100644
--- a/src/dracula.yml
+++ b/src/dracula.yml
@@ -506,6 +506,7 @@ tokenColors:
   - name: Comments
     scope:
     - comment
+    - punctuation.definition.comment
     settings:
       foreground: *COMMENT
```

**Comment by dsifford** [comment]
@joerohde Can you give a quick example screenshot of the issue? Having a hard time conceptualizing what you're describing.

Also, and possibly more importantly, did you say that you weren't able to send a pull request? If so, that's definitely a problem! What was the error message you received? 

Thanks so much! 😄

**Comment by joerohde** [comment]
@dsifford - PR - Could totally be me. To date I've always been a member or owner and used branch merges. I'll look into it more.  I don't have a trivial screen shot since I fixed it locally, and apologize for the bad description - This should help:

// Here is my comment

'//' will be white/punctuation general color
'Here is my comment' will be my comment color.

To date I've only seen this problem in the JS/Babel parser.

**Comment by dsifford** [comment]
Is this a separate language from VSCode's `javascript` language?

**Comment by joerohde** [comment]
Yes. It's [https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring](url).
Regular coloring works because it doesn't pull the leading '//' into a different syntax node.

I guess my main thought/concern is that if `punctuation.definition.keyword` has been given parity with 'keyword' for coloring, shouldn't that pattern be applied for any `punctuation.definition.*` not being explicitly overridden so that more detailed or unexpected-but-valid syntax trees don't create surprises?  For me personally the issue was only on the `punctuation.definition.comment`.

Also, looking at it more, I believe my need for the babel parser has become outdated and I can just take it out.  So really it's academic on what's the best thing to do.  <shrug>

**Comment by dsifford** [comment]
Agreed that there are several issues deeply engrained in the textmate scopes that could be argued one way or another. However, most of the other languages follow the same or closely similar conventions so I'm going to avoid specifically making this change on this end.

At the end of the day, I think it should be up to the maintainer of the babel language extension to decide whether or not he/she would like to conform to that same standard. That way the issue is handled across all themes, rather than just this one.
