### ISSUE TITLE
Changing to Dracula theme causes color issue in Insiders edition

### ISSUE THREAD

**Issue by heronsilva** [dracula/visual-studio-code#48]
When changing the editor theme to Dracula, some elements like borders and the file explorer's text turn red.
![dracula-theme-code-insiders](https://user-images.githubusercontent.com/9641348/29187241-69233aba-7de5-11e7-9300-80960e5c39fb.gif)

VS Code Insiders Version 1.16.0

**Comment by dsifford** [comment]
Yikes! I'll get this fixed as soon as the update is pushed to my distro's package manager.

**Comment by dsifford** [comment]
@heronsilva Just confirming: You don't have any `workbench.colorCustomizations` enabled correct? 

The reason I ask is that I'm noticing that you have a solid block line highlight, which is not the default.

Thanks for clarifying.

**Comment by heronsilva** [comment]
@dsifford No, I don't. The solid line highlight background is from another theme I use.

**Comment by dsifford** [comment]
I'm noticing now you said that this is affecting the insider's edition. 

Does this also happen to you on the latest version released today (1.15), or is it exclusively on insiders?

**Comment by heronsilva** [comment]
No, it's exclusive to the 'insiders' version.

**Comment by dsifford** [comment]
Hmm... Care to send a PR with the fix? Is this theme the only one that does it?

**Comment by heronsilva** [comment]
Yes, it's the only one. I switch between a couple of themes during the day XD
I'm currently trying to identify the issue, but, if I'm able to fix it, I'll send it ;)

**Comment by dsifford** [comment]
🙏 greatly appreciated. Let me know if you have any questions / issues with the code on this side of the fence and I'd be happy to clarify.

**Comment by jiku** [comment]
Same issue here with 2.1.3 in `code-insiders` 1.16.0. No issues with same version in `code` (1.15.0). Can't see it affecting any other themes.

**Comment by xekri** [comment]
The same issue here (code-insiders 1.16.0, macOS 10.12.6), I even thought it was a Easter egg..

**Comment by damosse31** [comment]
I confirm, same issue with Dracula Theme, no problem after uninstall theme

Code Insider 1.16 - Window 10

![screenshot_1](https://user-images.githubusercontent.com/16171524/29213536-eca3b388-7ea3-11e7-95b4-872234c2ad55.png)

**Comment by dsifford** [comment]
Are any of you able to try and fix? I'd rather not have to install the insiders version if I can avoid it.

**Comment by dsifford** [comment]
cc: @bpasero

**Comment by heronsilva** [comment]
@dsifford It looks like it's something with the build process, where, in the `dracula.yml` file, the colors that don't have a value assigned to them are converted to `null` in the ouput `.json` files.

Example:
##### `dracula.yml`:
`scrollbarSlider.activeBackground:                                             # Slider background color when active`

##### `dracula.json`:
`"scrollbarSlider.activeBackground": null,`

**Comment by heronsilva** [comment]
Sorry for the delay. Only now I could go back to take a look.

**Comment by dsifford** [comment]
Strange. Not sure why `null` values would be converted to that red shade. Is there an open issue for this in the main vscode repo?

**Comment by heronsilva** [comment]
I didn't found similar issue.
But, search the source code, I found this piece of code that has been updated recently:
https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/color.ts#L259

**Comment by dsifford** [comment]
Aha.. yep, that's definitely the culprit!

The fix is fairly straightforward. I can hammer that out real fast if you'd like unless you'd prefer to.

**Comment by heronsilva** [comment]
Well uh... I'll give it a try :)

**Comment by heronsilva** [comment]
I created a pull request in the vscode repo.
After all it wasn't an issue with the theme soo... closing it.

**Comment by dsifford** [comment]
Just pushed a fix. Sorry for the delay!

**Comment by heronsilva** [comment]
No problem :)
Glad to participate!
