### ISSUE TITLE
terminal.ansiBrightBlack is hard to see in integrated terminal

### ISSUE THREAD

**Issue by seanamosw** [dracula/visual-studio-code#49]
I find it very difficult to see things in the integrated terminal using this color.

![powershell too dark](https://user-images.githubusercontent.com/20722069/29211854-bda51e26-7e9b-11e7-91c2-fd7e6d234b23.png)

**Comment by dsifford** [comment]
Awaiting reply on this and then I'll fix: https://github.com/dracula/dracula-theme/issues/232#issuecomment-320544101

**Comment by dsifford** [comment]
@seanamosw Curious what command you have running that outputs BrightBlack on background? Trying out some other colors and there's really not much better I can do than what currently exists. BrightBlack on BG is just a poor color combination.

**Comment by seanamosw** [comment]
To clarify, in the original screenshot, the hard to see text is `* -Recurse -Force` which is just powershell highlighting in the terminal.
This using the powershell extension for the integrated terminal.

Some other colorful console loggers also use this color and it is very hard to see with the Dracula theme.
As a temporary workaround, I just changed the color to `#808080` so it is readable, at least to me on my screen.

![lighter](https://user-images.githubusercontent.com/20722069/29235169-d4f11bd2-7efc-11e7-839d-3f7c854aa77c.png)

Comparison with Monokai in ConEmu/Cmder:
![monokai](https://user-images.githubusercontent.com/20722069/29235267-c9a6e45e-7efd-11e7-9f3e-a39a366d560d.png)

**Comment by dsifford** [comment]
@seanamosw Could you try changing `terminal.background` to the theme's background color (#282A36) and see if that helps?

I think the issue is likely the fact that the integrated terminal background is a darkened variant of the editor's background color.

Thanks in advance!

**Comment by dsifford** [comment]
Switched the bg color back to default. Hopefully that helps.

**Comment by seanamosw** [comment]
Sorry I didn't get back to you sooner. Unfortunately, the improvement is marginal, if any. I'm still resorting to lightening the `terminal.ansiBrightBlack` color to `#808080` to get readability.

I've attached some console logging output to demonastrate.
Take note of the characters `[],={}`

Default 2.2.0, can barely see the characters.
![2.2.0](https://user-images.githubusercontent.com/20722069/29245844-ee513e28-7fe6-11e7-8c13-b27f1a8b4a74.png)

Modified `terminal.ansiBrightBlack`:
![modified](https://user-images.githubusercontent.com/20722069/29245847-099cfe38-7fe7-11e7-87f7-7fc34c1f08b0.png)

I have not tested on another display to see if it's universally difficult to see.

**Comment by seanamosw** [comment]
I thought I would add an example of what it looks in ConEmu with the Dracula ConEmu theme.

Not quite as light as my workaround, but still readable:
![conemu](https://user-images.githubusercontent.com/20722069/29253863-1c99b944-8088-11e7-83f7-57be7f8d972d.png)
