### ISSUE TITLE
Some parts of the editor aren't affected by the theme. 

### ISSUE THREAD

**Issue by shauryab98** [dracula/visual-studio-code#5]
The top title bar and the bottom status bar aren't affected by the theme.

![The way it's supposed to be.](https://cloud.githubusercontent.com/assets/2617705/20268725/611c9e82-aaa6-11e6-9a73-8202529f6bda.png)

![On my system](https://cloud.githubusercontent.com/assets/2617705/20268699/457f701e-aaa6-11e6-9ad8-dd7770a9b0e0.png)

**Comment by dsifford** [comment]
@shauryab98 Sorry for the tardiness on this. 

To my knowledge, it's not currently possible to style those parts of the editor. If this is incorrect, please let me know. 

Closing this for now.
