### ISSUE TITLE
Themes's colors whose value is null assume red by default

### ISSUE THREAD

**Issue by aeschli** [dracula/visual-studio-code#50]
_From @heronsilva on August 12, 2017 1:44_

- VSCode Version: 1.16.0-insider
- OS Version: Debian 9.1 / Ubuntu 16.04

Steps to Reproduce:

1. Install the 'Dracula' theme
2. Select any theme you have installed
3. Switcth to 'dracula' or 'dracula soft'
4. Elements in the editor should turn red, like borders, sidebar text, etc.

Reproduces without extensions: No

Screenshot:
![](https://user-images.githubusercontent.com/9641348/29187241-69233aba-7de5-11e7-9300-80960e5c39fb.gif)

_Copied from original issue: Microsoft/vscode#32359_

**Comment by aeschli** [comment]
It is a bug in the dracula theme to use 'null' as color value.
To disable a color, use a transparent color (e.g. #00000000)

**Comment by dsifford** [comment]
Thanks for the clarification @aeschli 😄 

Greatly appreciate you taking the time to reach out and clear up the confusion!
