### ISSUE TITLE
Theme improvements

### ISSUE THREAD

**Issue by ajitid** [dracula/visual-studio-code#54]
1. Inconsistency here! Please change blue color of key's quotes a bit to match behaviour of expand selection with yellow strings.
![peek 2017-09-19 19-42](https://user-images.githubusercontent.com/26769888/30596759-b3bb9ce6-9d72-11e7-81e9-0e344a0bf0f9.gif)

2. Dragging and dropping tabs shows a solid background. How about changing `"editorGroup.dropBackground": "#44475a"` to `"editorGroup.dropBackground": "#44475a70"` ?

3. Also please update screenshot in the readme. Thanks!

**Comment by dsifford** [comment]
PRs accepted

**Comment by ajitid** [comment]
PR done.
I'm on Ubuntu/Windows so I cannot update screenshot as I will not get a tinted titlebar which is available on a Mac.
