### ISSUE TITLE
Markdown syntax highlighting doesn't seem to be implemented

### ISSUE THREAD

**Issue by jmakeig** [dracula/visual-studio-code#6]
The code snippets work, but none of the Markdown syntax is highlighted.

## Dracula theme
<img width="617" alt="markdown-dracula" src="https://cloud.githubusercontent.com/assets/176233/20981155/4a5ff6ac-bc68-11e6-9068-677ddb825fdc.png">

## Visual Studio Dark theme
<img width="610" alt="markdown-vsdark" src="https://cloud.githubusercontent.com/assets/176233/20981154/4a5d1086-bc68-11e6-94b2-8ae5272adc6c.png">

**Comment by amandaporto** [comment]
Says this was closed and added - but I still don't have any syntax highlighting for markdown under this theme.
![atom-notes_md_ _webapp](https://user-images.githubusercontent.com/12819656/31079054-66565c22-a752-11e7-910e-7b9bbe351be9.png)
