### ISSUE TITLE
Highlight color of comments is hard to read

### ISSUE THREAD

**Issue by teddybradford** [dracula/visual-studio-code#61]
The find highlight color, selection highlight color, and selection highlight of a find highlighted color for comments are a bit difficult to read. Maybe they should be adjusted to improve readability?

<img width="546" alt="screen shot 2017-11-21 at 2 43 43 am" src="https://user-images.githubusercontent.com/3684553/33060322-d94910fa-ce65-11e7-8a28-df90c5783b64.png">

**Comment by dsifford** [comment]
I agree. It's a tricky situation though because VSCode stacks highlight color matches. So, for example, if `editor.selectionBackground` has some color with 50% opacity and `editor.selectionHighlightBackground` has some color with 50% opacity, the end result is two layers totaling 75% opacity over top of the text layer.

Feel free to open a PR if you've got any ideas.

**Comment by jbpotonnier** [comment]
Maybe add a border can help  `editor.selectionHighlightBorder`

**Comment by fungilation** [comment]
Just use a different background color that's contrasting to font color, while still a harmonious color of course. Like a soft shade of orange.

**Comment by dsifford** [comment]
Not possible to specify highlight background color based on semantics. It's a one-shot deal. So if background color is orange then the highlight color across the board will be orange. That also still leaves the issue of multiple overlaying highlight colors as described above.

**Comment by beeb** [comment]
Similar to my other issue https://github.com/dracula/visual-studio-code/issues/134 , one could change the comments color to a lighter shade with reduced opacity, e.g. `#8aa1e59b` which gives:

<img width="344" alt="Screenshot 2020-03-11 at 08 00 55" src="https://user-images.githubusercontent.com/703631/76390854-77761080-636e-11ea-94a6-1399f90c7748.png">

**Comment by MiguelGuthridge** [comment]
Just bumping to ask if there's going to be a fix for this? To me, it looks like selections are exactly the same colour as the highlights that VS Code does for matching words. Any guesses on which ones of these I have selected and which ones are highlighted? I'm not even sure anymore and I was the one that made the selections.
![image](https://user-images.githubusercontent.com/31365175/127444999-96b4af79-fb36-4fbb-9c6b-6732c49abd7e.png)
