### ISSUE TITLE
Operator Mono Font problem 

### ISSUE THREAD

**Issue by MBehtemam** [dracula/visual-studio-code#62]
first thanks for your awesome theme my problem is when i use operator mono font i cant get best result forexample see these pictures. the first one is operator mono font with one dark pro thene :
![One Dark Pro](https://user-images.githubusercontent.com/1811124/33682724-aebbfec2-dadd-11e7-9338-19d3c2b80203.png)

and below is dracula theme with same config with operator mono font 

![dracula](https://user-images.githubusercontent.com/1811124/33682798-ed9cc9d2-dadd-11e7-8cc5-9b0281d9c3e0.png)

can i get result of operator mono theme like one dark pro in dracula theme ?

**Comment by dsifford** [comment]
@MBehtemam Can you clarify what you mean? Not sure I’m understanding you completely. What’s the issue?

**Comment by MBehtemam** [comment]
i know that font is effected in dracula theme but see the `className` word is italic in drak pro but in dracula it's normal , is it related to dracula and if yes how can i fix this ?

**Comment by the94air** [comment]
He ment that the html attribute is not italic in the second theme.
> How to make the html attributes italic?

**Comment by dsifford** [comment]
@the94air This should be fixed now. Is it not?

**Comment by the94air** [comment]
It really depend on the theme that you use as of some of them makes it italic and others are not. I am not suffering from the same issue. I just want to make sure that you understand what the issue.., that's all :smile:
