### ISSUE TITLE
can't uninstall theme

### ISSUE THREAD

**Issue by sunsteam** [dracula/visual-studio-code#64]
I tried disable plugin and restart vscode and do again but still can't uninstall theme , please see the screenshot. It stuck on this step.

![2017-12-25 17:32 10](https://user-images.githubusercontent.com/7489390/34337419-191ef592-e99a-11e7-93d3-679dbd79d8c9.png)

vs code version: 1.19.1
system: macOS 10.12.6

**Comment by dsifford** [comment]
Not sure why this could be happening, but worst-case scenario you can always remove the theme from your `~/.vscode/extensions` directory manually and that should have the same effect.
