### ISSUE TITLE
This theme is missing for unknown reasons after updating. 

### ISSUE THREAD

**Issue by paperant** [dracula/visual-studio-code#65]
I have installed this theme for several months. But with the recent two or three releases this theme always disappeared from my installed extension list. And every time I have to search for it and reinstall it. 

I'm using VS Code(v1.19.3) on MacBook Pro with macOS version 10.13.1.

Anyone troubled by the same problem with me?

**Comment by dsifford** [comment]
Not sure why that could be happening. I've never ran into this issue.

I'll leave this issue open so hopefully others can chime in.

**Comment by paperant** [comment]
Seems this is a bug of the VS Code editor. It was mentioned [HERE](https://github.com/Microsoft/vscode/issues/41894). 
I'll close this issue. Thank you for helping.

**Comment by dsifford** [comment]
Thanks for the update!
