### ISSUE TITLE
We plan to feature your VS Code extension!

### ISSUE THREAD

**Issue by auchenberg** [dracula/visual-studio-code#71]
Hi,

It's Kenneth from VS Code. I'm reaching out to tell you that we plan to feature your awesome VS Code extension on our marketplace https://marketplace.visualstudio.com/#VSCode in the next iteration.

Please work with your community to resolve any major issues, as you'll probably see a significant bump in new users trying your extension.

Thanks for the great work, and happy coding!

/k

Kenneth Auchenberg
Visual Studio Code
Program Manager, Microsoft

**Comment by zenorocha** [comment]
That's awesome! Thanks for letting us know ;)

**Comment by dsifford** [comment]
Woo! Thanks so much :blush:
