### ISSUE TITLE
Script tag in HTML files breaks highlighting subsequent HTML tags

### ISSUE THREAD

**Issue by romellem** [dracula/visual-studio-code#76]
When I have a script tag, it breaks all subsequent closes tags (i.e., the closing `</script>`, `</body>`, and `</html>` in this screenshot):

![screen shot 2018-06-01 at 11 41 13 am](https://user-images.githubusercontent.com/8504000/40852780-4a8f9cf8-6591-11e8-8204-4d3642cf905e.png)

I noticed that if I have a bad `type` attribute, then highlighting the closing tags is correct, although the JS highlighting in the `script` tag is disabled:

![screen shot 2018-06-01 at 11 42 05 am](https://user-images.githubusercontent.com/8504000/40852815-6c8fb144-6591-11e8-962f-9ccd28c7842a.png)

I _think_ this is related to this repo, since when I disable this theme, highlighting appears correct.

**Comment by dsifford** [comment]
@romellem Thanks for the report.

Can you confirm this still happens if you spell Javascrip**t** correctly in the `type` attribute?

It should read `<script type="text/javascript">`

**Comment by romellem** [comment]
Sorry, I wasn't very clear. I meant if you have a regular tag with normal attributes, the highlighting breaks.

So `<script>` or `<script type="text/javascript">` and it looks broken:

<img width="402" alt="screen shot 2018-06-01 at 7 49 15 pm-fs8" src="https://user-images.githubusercontent.com/8504000/40868693-06761440-65d5-11e8-9c13-7ec1493f8c7d.png">

But insert a bad value, and the HTML tags now highlight correctly (albeit with non-highlighted JS):

<img width="462" alt="screen shot 2018-06-01 at 7 51 17 pm-fs8" src="https://user-images.githubusercontent.com/8504000/40868712-3c6c59a6-65d5-11e8-9d6f-9c2d623ddcb4.png">

**Comment by romellem** [comment]
Also, I am on:

- macOS 10.12.6
- VS Code Version 1.23.1
- Dracula Official version 2.10.0.

**Comment by dsifford** [comment]
Hm...

Here's what I'm getting:

![image](https://user-images.githubusercontent.com/5240018/40868837-64597c3c-65df-11e8-9b4c-96f3eac13d53.png)

Can you try disabling your other extensions and see if the issue persists?

**Comment by romellem** [comment]
Ah ha! Good suggestion.

Looks like this extension [Sublime Babel](https://github.com/joshpeng/Sublime-Babel-VSCode) is causing compatibility issues. When I disable that extension, everything highlights as you'd expect.

Thanks again for the troubleshooting tip.

> <img width="480" alt="screen shot 2018-06-01 at 8 13 54 pm-fs8" src="https://user-images.githubusercontent.com/8504000/40868943-678ad6be-65d8-11e8-8528-52e04397f997.png">

**Comment by hrdtbs** [comment]
[Babel JavaScript](https://github.com/michaelgmcd/vscode-language-babel)  is causing this issues too.
