### ISSUE TITLE
Strange dark green  color on warnings

### ISSUE THREAD

**Issue by DanielRamosAcosta** [dracula/visual-studio-code#77]
In the file explorer, warnings appear green, I don't really know if it's an issue with Dracula theme or `tslint`, here is a screenshot:

![image](https://user-images.githubusercontent.com/11427028/41355129-a8f91aa4-6f18-11e8-8726-e286d1b011d4.png)

**Comment by dsifford** [comment]
Nice catch!

All fixed in `2.11.0`.
