### ISSUE TITLE
normal fontStyle only

### ISSUE THREAD

**Issue by hismichael** [dracula/visual-studio-code#78]
Can we also have a theme that is with normal fontStyle only? no italic, no underline. Since for people poorly eye-sighted like me, italic and underline words are actually difficult to read.

**Comment by dsifford** [comment]
@hismichael Always happy to help out where I can for visually impaired users.

I'll add this to the todo list. :+1:

**Comment by hismichael** [comment]
Great!

**Comment by gibbok** [comment]
@dsifford Great work on this theme, I would like to ask you if you have any update on this ticket... Would be great to have the option to disable italic and underline.

@hismichael meanwhile you [can use this work](https://stackoverflow.com/questions/44219768/disable-italic-syntax-highlighting-in-vs-code/49202435#49202435) around, basically you disable the italic in vscode instead that in the theme.

Keep up the good work!

**Comment by jeffteixeira** [comment]
@dsifford congratulations on your work on the dracula theme. I would like to know if you hear any updates related to this issue.

**Comment by jeffteixeira** [comment]
Hi. Any news?

**Comment by adityamwagh** [comment]
I want to know about this too.

**Comment by jeffteixeira** [comment]
A possible workaround: https://github.com/microsoft/vscode/issues/32579#issuecomment-341502559

**Comment by jeffteixeira** [comment]
How complex would it be to implement this functionality @dsifford?

**Comment by jeffteixeira** [comment]
I have difficulties reading italic text

**Comment by jeffteixeira** [comment]
On screens with HD resolution or lower (which is my case), italicized texts are not very readable @dsifford

**Comment by dsifford** [comment]
All: I hear you and understand that this is an issue that faces many, many people. I personally think the ability to opt out of text formatting should be a feature at the editor level, and should not be the responsibility for every theme maintainer. I have reached out to the team at Microsoft about this via email a few weeks ago and will report back with any updates as they roll in.

Appreciate the patience.

**Comment by jeffteixeira** [comment]
We thanks you :)

**Comment by jeffteixeira** [comment]
In the vim editor, the dracula theme has the option to disable italic texts by adding the line `let g: dracula_italic=0` in the configuration file. Is it really the editor's responsibility to do this?

**Comment by dsifford** [comment]
@jeffteixeira I maintain the vim implementation as well.

Yes, it is the editor's responsibility because vim and VSCode fundamentally do not work the same way.

**Comment by jeffteixeira** [comment]
Ok

**Comment by dsifford** [comment]
All: See the issue linked above (microsoft/vscode#32579) for more context, but I just received word from a program manager at Microsoft that they are prioritizing the issue since it impacts accessibility.

See that issue also for a short-term workaround.
