### ISSUE TITLE
Find all references popup window is hard to see

### ISSUE THREAD

**Issue by bn4z** [dracula/visual-studio-code#81]
When opening the `Find All References` (Shift F12 shortcut) popup it's difficult to see the limit between the popup window and the code behind it. On the screenshot below the limit is marked with the red dashed line.

![image](https://user-images.githubusercontent.com/3406749/43447471-e221bab2-94ab-11e8-8adc-16044879389a.png)

I guess this is not specific to this popup. Any popup should have a different color. I suppose, a slightly brighter background would do the job. Or maybe a pure dark `#000000`

![image](https://user-images.githubusercontent.com/3406749/43447911-d981ecb4-94ac-11e8-8349-558ab46decc3.png)

This is `Javascript` but I believe this applies to any language.

**Comment by seiks** [comment]
I second this. While the popup does follow Dracula's color scheme, it is incredibly hard to differentiate.

**Comment by Delapouite** [comment]
I agree about the lack of contrast. Here's the tweaks I've added to my User Settings:

```json
"workbench.colorCustomizations": {
    "[Dracula]": {
        "peekView.border": "#BD93F9",
        "peekViewEditor.background": "#21222C",
        "peekViewResult.background": "#191A21",
        "editorHoverWidget.border": "#BD93F9",
        "editorHoverWidget.background": "#21222C"
    }
},

```
