### ISSUE TITLE
[JavaScript] All variables within an export default block are treated as alias real names

### ISSUE THREAD

**Issue by rmtracey** [dracula/visual-studio-code#82]
It seems that all variables within an `export default` block in JavaScript are treated as the "real name" of an alias, and are therefore rendered as italicized orange characters, rather than white ones as they usually are. This results in some very wrong-looking syntax highlighting if you have anything other than references to your exports in that block.

This is especially a problem for writing single-file components in Vue, where the recommended style is to write all the code for your components within an `export default` block.

I'm not entirely sure if this is something that you guys are able to fix (or if it's more of an issue with VSCode), but if you can, it'd be greatly appreciated.

Screenshot:
![image](https://user-images.githubusercontent.com/3460875/43865227-f64dac78-9b2f-11e8-8f4d-1768755650b5.png)

**Comment by dsifford** [comment]
Pretty awesome catch, @rmtracey!

I'm fairly certain this is going to be an issue for the [TypeScript-TmLanguage](https://github.com/Microsoft/TypeScript-TmLanguage) repo. Would you mind opening an issue up there and cross-reference this thread?

Thanks!

**Comment by rmtracey** [comment]
@dsifford Done, thanks for pointing me in the right direction!

**Comment by dsifford** [comment]
I think this will require too much effort to fix. Since this is such a niche case, I'm gonna just leave it as-is for now.

If it bugs you too much, just define your object outside of the export and then export it after.

**Comment by dsifford** [comment]
@rmtracey Just kidding... I think I can actually fix this rather easily... I'll push it out with the adjustments I make for the latest release (in the next few days).
