### ISSUE TITLE
Npm run build Error: Failed at the theme-dracula@2.12.1 build script.

### ISSUE THREAD

**Issue by reinerluke** [dracula/visual-studio-code#83]
NPM Error: 
![grafik](https://user-images.githubusercontent.com/30616142/44140715-31074ebe-a07b-11e8-9b7d-8e672d44770a.png)

Log File:
[2018-08-15T09_02_28_286Z-debug.log](https://github.com/dracula/visual-studio-code/files/2289751/2018-08-15T09_02_28_286Z-debug.log)

NPM Version: 5.6.0

**Comment by dsifford** [comment]
Should be good now.

**Comment by reinerluke** [comment]
All fine now! Thanks
