### ISSUE TITLE
After upgrading to VSCode 1.26 variables changed color in JavaScript

### ISSUE THREAD

**Issue by vshab** [dracula/visual-studio-code#84]
Right now `const` variable are purple, `let` and `var` variables  are yellow. 

![code](https://user-images.githubusercontent.com/6755908/44143703-e358df50-a0ae-11e8-9470-69cc8d4ed5a7.png)

Both used to be white:
<img width="412" alt="screen shot 2018-08-15 at 17 17 53" src="https://user-images.githubusercontent.com/6755908/44143787-3902bae8-a0af-11e8-9c6e-04e23ffa5b35.png">

**Comment by dsifford** [comment]
Thanks for the report. I'll check into this once I'm able to upgrade. (My distro's package is currently segfaulting from the changes).

**Comment by dabrowski-adam** [comment]
Hey, I'm pretty sure that pseudo-constants, e.g. `var MAGIC_NUMBER = 4;` were *not* white before, but purple. And now they are white.

**Comment by dsifford** [comment]
@dabrowski-adam They changed what constitutes as a constant. 

Before the change, only all caps const variables counted. Now all const variables count, which I disagree with. 

Leaving pseudo-constants purple after the change is too much purple.

**Comment by dabrowski-adam** [comment]
@dsifford I agree with you—the other types of variables shouldn't be purple—but it was nice to have those all caps pseudo-constants stand out. So now it would require a custom grammar?

**Comment by dsifford** [comment]
@dabrowski-adam either that or you’d have to convince the syntax maintainers for js and ts to revert back to its old behavior

**Comment by dsifford** [comment]
Good catch @n1ghtmare 

Fixed in `v2.14.1`. Pushing out to the marketplace now. :+1:

**Comment by AndreCosta101** [comment]
Hello,

My version is 2.21.0 and my variables are all purple in VSCode. Where can I revert it back to white?

thank you

**Comment by dsifford** [comment]
@bdielman is looking into making an adjustment specifically with js/ts (see #148).

If you want to simply disable, you can in your usersettings by turning off semantic highlighting.

**Comment by AndreCosta101** [comment]
Thank you so much =)
