### ISSUE TITLE
New 1.26 breadcrumbs menu needs styling

### ISSUE THREAD

**Issue by seiks** [dracula/visual-studio-code#85]
Hi!

The new breadcrumbs feature needs styling. If I'm not mistaken, the current menu uses default Dark+ colors. The menu definitely appears as being too yellow in tone in my eyes.

**Dark+**
![Dark+](https://user-images.githubusercontent.com/22685871/44296810-433f8880-a2ce-11e8-85d0-0c0c7ae1f5d3.png)

**Dracula**
![Dracula](https://user-images.githubusercontent.com/22685871/44296788-f78cdf00-a2cd-11e8-8031-ee864dcb4a96.png)

The contrast might be hard to differentiate from these screenshots due to GItHub's white background color miscalibrating your eyes, so I would suggest to try this out in your own editor and see for yourself.

**Comment by dsifford** [comment]
Thanks for the report. 

Still haven't been able to update to 1.26 due to a [segfault issue on Arch Linux](https://github.com/Microsoft/vscode/issues/55934) machines. The fix was recently made so perhaps I can get around to adjusting sometime this weekend when I download the update.
