### ISSUE TITLE
Not highlight in css inline

### ISSUE THREAD

**Issue by willian-fer** [dracula/visual-studio-code#86]
Since the last updates it looks like this

![image](https://user-images.githubusercontent.com/33581079/44486178-3baf1500-a629-11e8-80c6-5734c1858faa.png)

**Comment by dsifford** [comment]
Thanks for the report. Just checked this out and it looks like an issue with the syntax itself (all inlined css is being scoped entirely to `source.css`, rather than importing and applying the css syntax in place).

You may want to try opening this one up in the syntax repo. I'll keep this issue open to follow along.

**Comment by dsifford** [comment]
Closing due to this being out of scope.

**Comment by jamilabreu** [comment]
@dsifford is the closing quote not being the correct color also a syntax issue? if yes, which is the syntax repo i should be looking at? thanks!!

**Comment by dsifford** [comment]
The closing quote has `source.css` as the highest priority scope. The opening quote has `punctuation.definition.string.begin` as the highest priority scope.

So it's either an issue with html syntax or css syntax. Not sure off the top of my head.

**Comment by jamilabreu** [comment]
@dsifford  ah, interesting! any direction at all (might you know someone that knows?) on where to report this would be super appreciated -  googling has been a dead end for me :/

**Comment by dsifford** [comment]
No concrete people I can point you to for this, but maybe this will help...

First, it's helpful to just be aware of  <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> -> `Developer: Inspect TM Scopes` command.

And with that in mind, the upstream repos for the HTML and CSS syntaxes are [here](https://github.com/textmate/html.tmbundle/blob/master/Syntaxes/HTML.plist) and [here](https://github.com/octref/language-css/blob/master/grammars/css.cson) respectively.
