### ISSUE TITLE
SASS theme issue - Hex and Unit values

### ISSUE THREAD

**Issue by dkouvdis** [dracula/visual-studio-code#9]
Hex and unit values were previously yellow, now it's white after the update. 
Not sure if it was intentional.

![image](https://cloud.githubusercontent.com/assets/2727196/23406913/fe4b4944-fdc9-11e6-8870-eb8b262dda4c.png)

**Comment by dsifford** [comment]
That's for the report. Not intentional. Will fix shortly.
