### ISSUE TITLE
Faded/Dimmed colours on MacOS Mojave

### ISSUE THREAD

**Issue by edercampelo** [dracula/visual-studio-code#92]
hi there,

after update my mac to macOS Mojave 10.14.1 seems like the colours are not the same (vibrant colours) anymore . The colours seems a little bit dimmed/faded. I tested on another mac and I'm getting the same issue.

![screen shot 2018-11-14 at 3 30 48 pm](https://user-images.githubusercontent.com/2735838/48460321-83a59880-e822-11e8-9163-9fe3a2ddc048.png)

**Comment by dsifford** [comment]
Are you perhaps using the "dracula-soft" variant of the theme? If not, I'm not sure what could be causing this, but happy to keep this issue open until something turns up. :+1:

**Comment by oefterdal** [comment]
Try change your font to bold.

**Comment by Nemesis19** [comment]
happens on VSCode 1.31.1 on mac os high sierra as well...colors seems softer while using the regular Dracula theme.

**Comment by rumkin** [comment]
Colors happened fade for me too this week.

**Comment by rumkin** [comment]
Solved after restart. Seems like VSCode uses this trick to make each update look brighter and more exciteful.

**Comment by hacknug** [comment]
Is this an issue anymore? Can we close it?

**Comment by dsifford** [comment]
Yep, good to close. Upstream issue with electron. See #130.
