### ISSUE TITLE
Class methods has different colors.

### ISSUE THREAD

**Issue by emilbryggare** [dracula/visual-studio-code#93]
Class methods are colored differently.

![image](https://user-images.githubusercontent.com/1659740/49295115-388fb480-f4b5-11e8-9e1e-7df81fc168d6.png)

My guess is that some keywords are reserved for JavaScript and has higher priority than class methods.

Visual Code Version 1.29.1
Dracula version 2.15.0

**Comment by hacknug** [comment]
@emilbryggare this seem to work correctly now. Can you confirm if that's the case on your end too?

```js
class Rectangle {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }

  method() {
    return this.width;
  }

  delete() {
    return this.height;
  }
}

const r = new Rectangle(1, 2);
r.delete();
r.method();
```

**Comment by emilbryggare** [comment]
![image](https://user-images.githubusercontent.com/1659740/73400149-6af59700-429d-11ea-8bf4-8ac122d1958c.png)

@hacknug confirmed everything is working well now.
