### ISSUE TITLE
Unable to identify whether an element is selected or not

### ISSUE THREAD

**Issue by byyxx128** [dracula/visual-studio-code#96]
See the GIF directly.
![bug](https://user-images.githubusercontent.com/20079289/52534770-94778480-2d13-11e9-84ec-802d6ea3e96f.gif)
Dracula uses the same background color for a word which is selected or which is just highlighted.

**Comment by dsifford** [comment]
This has been reported several times in the past. It's particularly difficult to handle with VSCode due to how VSCode layers highlights in the editor. 

Ping @DanielRamosAcosta --- Any thoughts here?

**Comment by DanielRamosAcosta** [comment]
I'll take a look later today 😄

**Comment by DanielRamosAcosta** [comment]
Hey @dsifford, can I have a quick way to chat with you? maybe Telegram/Slack or something

**Comment by dsifford** [comment]
https://draculatheme.slack.com

**Comment by DanielRamosAcosta** [comment]
It seems like I need an invitation or something, could you invite me please? danielramosacosta@hotmail.com

**Comment by dsifford** [comment]
There's a link in the readme [here](https://github.com/dracula/dracula-theme) you can click to join.

**Comment by byyxx128** [comment]
Any idea about this?

**Comment by jb8893** [comment]
I'm having the same issue :pensive:

**Comment by byyxx128** [comment]
I have tried lots of themes. More than half of them have the same issue, but the rest do not. So I believe there should be a solution for it, although I don't what it is.

**Comment by byyxx128** [comment]
@dsifford Good news! I have found the corresponding values!
`editor.selectionBackground`
`editor.lineHighlightBackground`
`list.activeSelectionBackground`
`list.hoverBackground`
Please check and modify these keys.

**Comment by byyxx128** [comment]
Why did no one answer me...😑
Shall I post a PR?

**Comment by dsifford** [comment]
@byyxx128 This problem is trickier than just identifying the scope names.. 

See here for more info: https://github.com/dracula/visual-studio-code/issues/61#issuecomment-346242336

**Comment by byyxx128** [comment]
OK, I totally understand. The problem is related to overlying opacity rather than just to choose colors.
