### ISSUE TITLE
Theme is different than what it should be.

### ISSUE THREAD

**Issue by TaeyoonKwon** [dracula/visual-studio-code#98]
I've installed Dracula Official extension from Visual Studio Code, and applied it, and I see the difference from what there is on the website.

Mine

![Diff](https://i.imgur.com/Dx1k7eU.png)

On Website

![Image](https://camo.githubusercontent.com/d695efd1815607a9056ea5817501adc0a63632ca/68747470733a2f2f64726163756c617468656d652e636f6d2f6173736574732f696d672f73637265656e73686f74732f7673636f64652e706e67)

You can see there are many differences such as the color of .getDate(), color or this keyword (it is also italic on my pc.) And so on.

Why is it different and is there a way to apply the one shown on the website?

Is the screenshot on the website outdated? Or am I missing something?

**Comment by dsifford** [comment]
Yes, the screenshot on the website is extremely outdated. My fault there.

This implementation (and the vim implementation for which I also maintain) tries to stick as close as possible to the specification doc which can be found here https://dsifford.github.io/dracula-spec/
